import { assertEquals, assertMatch, assertStringIncludes } from "@std/assert";
import {
  replaceWithSymlink,
  runCli,
  snapshotTree,
  withGoodTree,
  writeFile,
} from "../src/testing.ts";

const COPY = "skills/review-writer/references/vendor/verdict-format.md";
const MANIFEST = "vendor-manifest.json";

// deno-lint-ignore no-explicit-any
type Json = any;

async function readManifest(root: string): Promise<Json> {
  return JSON.parse(await Deno.readTextFile(`${root}/${MANIFEST}`));
}

async function writeManifest(root: string, manifest: Json): Promise<void> {
  await Deno.writeTextFile(
    `${root}/${MANIFEST}`,
    JSON.stringify(manifest, null, 2) + "\n",
  );
}

function kindsOf(lines: string[]): string[] {
  return lines.map((line) => line.slice(0, line.indexOf(":")));
}

Deno.test("gen leaves an already generated tree byte identical", async () => {
  await withGoodTree(async (root) => {
    const before = await snapshotTree(root);
    const result = await runCli(["gen", "--root", root]);
    assertEquals(result.code, 0, result.stderr.join("\n"));
    assertEquals(await snapshotTree(root), before);
  });
});

Deno.test("generating twice from the same input is byte identical", async () => {
  await withGoodTree(async (root) => {
    await Deno.remove(`${root}/${COPY}`);
    assertEquals((await runCli(["gen", "--root", root])).code, 0);
    const first = await snapshotTree(root);
    assertEquals((await runCli(["gen", "--root", root])).code, 0);
    assertEquals(await snapshotTree(root), first);
  });
});

Deno.test("a vendored copy carries the do-not-edit header, its id and its source digest", async () => {
  await withGoodTree(async (root) => {
    await Deno.remove(`${root}/${COPY}`);
    assertEquals((await runCli(["gen", "--root", root])).code, 0);
    const written = await Deno.readTextFile(`${root}/${COPY}`);
    const digest =
      (await readManifest(root)).lock.resolutions["verdict-format"].digest;
    assertEquals(written.split("\n").slice(0, 4), [
      "<!-- DO NOT EDIT. Generated by vendor.ts. -->",
      "<!-- contract: verdict-format -->",
      `<!-- source-digest: ${digest} -->`,
      "",
    ]);
  });
});

Deno.test("a vendored copy holds the canonical contract body", async () => {
  await withGoodTree(async (root) => {
    await Deno.remove(`${root}/${COPY}`);
    assertEquals((await runCli(["gen", "--root", root])).code, 0);
    const written = await Deno.readTextFile(`${root}/${COPY}`);
    const source = await Deno.readTextFile(
      `${root}/contracts/verdict-format.md`,
    );
    assertEquals(
      written.split("\n").slice(4).join("\n"),
      source.slice(source.indexOf("# Verdict Format")),
    );
  });
});

Deno.test("gen refuses a contract that has never been accepted and writes nothing", async () => {
  await withGoodTree(async (root) => {
    const manifest = await readManifest(root);
    delete manifest.lock.resolutions["verdict-format"];
    await writeManifest(root, manifest);
    const before = await snapshotTree(root);

    const result = await runCli(["gen", "--root", root]);
    assertEquals(result.code, 1);
    assertEquals(kindsOf(result.stdout), ["unresolved"]);
    assertEquals(await snapshotTree(root), before);
  });
});

Deno.test("gen refuses a canonical text that drifted from its resolution and writes nothing", async () => {
  await withGoodTree(async (root) => {
    await Deno.writeTextFile(
      `${root}/contracts/verdict-format.md`,
      await Deno.readTextFile(`${root}/contracts/verdict-format.md`) +
        "\nOne more rule.\n",
    );
    const before = await snapshotTree(root);

    const result = await runCli(["gen", "--root", root]);
    assertEquals(result.code, 1);
    assertEquals(kindsOf(result.stdout), ["unaccepted-drift"]);
    assertStringIncludes(result.stdout[0], "verdict-format");
    assertEquals(await snapshotTree(root), before);
  });
});

Deno.test("gen refuses a declared contract with no canonical file and writes nothing", async () => {
  await withGoodTree(async (root) => {
    await Deno.remove(`${root}/contracts/verdict-format.md`);
    const before = await snapshotTree(root);

    const result = await runCli(["gen", "--root", root]);
    assertEquals(result.code, 1);
    assertEquals(kindsOf(result.stdout), ["closure"]);
    assertEquals(await snapshotTree(root), before);
  });
});

Deno.test("gen removes a vendored copy no declaration accounts for", async () => {
  await withGoodTree(async (root) => {
    const orphan = "skills/release-notes/references/vendor/orphan.md";
    await writeFile(`${root}/${orphan}`, "left over from an old declaration\n");

    assertEquals((await runCli(["gen", "--root", root])).code, 0);
    assertEquals((await snapshotTree(root)).has(orphan), false);
  });
});

Deno.test("adding a dependency on an already resolved contract needs no acceptance", async () => {
  await withGoodTree(async (root) => {
    const skill = `${root}/skills/release-notes/SKILL.md`;
    await Deno.writeTextFile(
      skill,
      (await Deno.readTextFile(skill)).replace(
        "    - changelog-entry\n",
        "    - changelog-entry\n    - verdict-format\n",
      ),
    );

    const result = await runCli(["gen", "--root", root]);
    assertEquals(
      result.code,
      0,
      result.stdout.concat(result.stderr).join("\n"),
    );
    assertEquals(
      (await readManifest(root)).lock.dependencies["release-notes"],
      ["changelog-entry", "verdict-format"],
    );
    assertStringIncludes(
      await Deno.readTextFile(
        `${root}/skills/release-notes/references/vendor/verdict-format.md`,
      ),
      "# Verdict Format",
    );
  });
});

Deno.test("gen refuses a skill whose declaration cannot be read and keeps its vendored copies", async () => {
  await withGoodTree(async (root) => {
    const skill = `${root}/skills/review-writer/SKILL.md`;
    await Deno.writeTextFile(
      skill,
      (await Deno.readTextFile(skill)).replace(
        "metadata:\n",
        "metadata:\n  audience: internal\nmetadata:\n",
      ),
    );
    const before = await snapshotTree(root);

    const result = await runCli(["gen", "--root", root]);
    assertEquals(result.code, 2);
    assertEquals(result.stdout, []);
    assertStringIncludes(result.stderr.join("\n"), "error:");
    assertEquals(await snapshotTree(root), before);
  });
});

Deno.test("gen refuses a vendor directory symlinked outside the tree", async () => {
  await withGoodTree(async (root) => {
    const outside = `${root.slice(0, root.lastIndexOf("/"))}/outside`;
    await Deno.mkdir(outside, { recursive: true });
    await replaceWithSymlink(
      `${root}/skills/release-notes/references/vendor`,
      outside,
    );
    const outsideBefore = await snapshotTree(outside);

    const result = await runCli(["gen", "--root", root]);
    assertEquals(result.code, 2);
    assertEquals(result.stdout, []);
    assertStringIncludes(result.stderr.join("\n"), "error:");
    assertEquals(await snapshotTree(outside), outsideBefore);
  });
});

Deno.test("gen refuses a symlink planted at the manifest temporary path", async () => {
  await withGoodTree(async (root) => {
    const outside = `${root.slice(0, root.lastIndexOf("/"))}/outside`;
    await writeFile(`${outside}/target.json`, "must not be overwritten\n");
    await Deno.remove(`${root}/${COPY}`);
    await replaceWithSymlink(
      `${root}/${MANIFEST}.tmp`,
      `${outside}/target.json`,
    );

    const result = await runCli(["gen", "--root", root]);
    assertEquals(result.code, 2);
    assertEquals(result.stdout, []);
    assertEquals(
      await Deno.readTextFile(`${outside}/target.json`),
      "must not be overwritten\n",
    );
  });
});

Deno.test("gen exits 2 naming the path when a vendored copy cannot be written", async () => {
  await withGoodTree(async (root) => {
    await Deno.remove(`${root}/${COPY}`);
    await Deno.mkdir(`${root}/${COPY}`);

    const result = await runCli(["gen", "--root", root]);
    assertEquals(result.code, 2);
    assertEquals(result.stdout, []);
    assertStringIncludes(result.stderr.join("\n"), "verdict-format.md");
  });
});

Deno.test("a run interrupted by an unwritable copy leaves every other file in place", async () => {
  await withGoodTree(async (root) => {
    const blocked = "skills/review-writer/references/vendor/changelog-entry.md";
    await Deno.remove(`${root}/${blocked}`);
    await Deno.mkdir(`${root}/${blocked}`);

    assertEquals((await runCli(["gen", "--root", root])).code, 2);
    const after = await snapshotTree(root);
    assertEquals(after.has(COPY), true);
    assertEquals(after.has(MANIFEST), true);
    assertEquals(
      after.has("skills/release-notes/references/vendor/changelog-entry.md"),
      true,
    );
  });
});
