import { assertEquals, assertStringIncludes } from "@std/assert";
import type { Sink } from "../src/vendor.ts";
import { runCli, snapshotTree, withEmptyDir, withGoodTree } from "./helpers.ts";

const SOURCE = new URL("../src/vendor.ts", import.meta.url).pathname;

/**
 * Loads a copy of the tool with one edit applied, standing in for the file
 * having been altered between the digest a consumer checked and the run.
 */
async function runAltered(
  dir: string,
  find: string,
  replaceWith: string,
): Promise<{ code: number; stdout: string[] }> {
  const source = await Deno.readTextFile(SOURCE);
  assertStringIncludes(source, find);
  const path = `${dir}/altered.ts`;
  await Deno.writeTextFile(path, source.replace(find, replaceWith));

  const module = await import(`file://${path}`) as {
    run: (argv: string[], out: Sink, err: Sink) => Promise<number>;
  };
  const stdout: string[] = [];
  const code = await module.run(["self-test"], (l) => stdout.push(l), () => {});
  return { code, stdout };
}

Deno.test("self-test passes against the vectors the file carries", async () => {
  const result = await runCli(["self-test"]);
  assertEquals(result.stdout, []);
  assertEquals(result.code, 0);
});

Deno.test("self-test reads no file, so it runs against a root that does not exist", async () => {
  const result = await runCli(["self-test", "--root", "/no/such/tree"]);
  assertEquals(result.code, 0);
});

Deno.test("self-test leaves the tree it is pointed at untouched", async () => {
  await withGoodTree(async (root) => {
    const before = await snapshotTree(root);
    assertEquals((await runCli(["self-test", "--root", root])).code, 0);
    assertEquals(await snapshotTree(root), before);
  });
});

Deno.test("self-test fails when the digest it computes stops matching its vector", async () => {
  await withEmptyDir(async (dir) => {
    // Stops the blank lines after the frontmatter from being absorbed into
    // the separator, which changes what every contract digests to.
    const result = await runAltered(
      dir,
      'while (start < lines.length && lines[start] === "") start++;',
      'while (start < lines.length && lines[start] === "\\u0000") start++;',
    );
    assertEquals(result.code, 1);
    assertEquals(result.stdout.length > 0, true);
    assertStringIncludes(result.stdout.join("\n"), "self-test:");
  });
});

Deno.test("self-test fails when the vendored copy header stops matching its vector", async () => {
  await withEmptyDir(async (dir) => {
    const result = await runAltered(
      dir,
      "<!-- DO NOT EDIT. Generated by ${GENERATOR.name}. -->",
      "<!-- DO NOT EDIT. Made by ${GENERATOR.name}. -->",
    );
    assertEquals(result.code, 1);
    assertStringIncludes(result.stdout.join("\n"), "self-test:");
  });
});

Deno.test("self-test fails when the conformance framing stops matching its vector", async () => {
  await withEmptyDir(async (dir) => {
    const result = await runAltered(
      dir,
      "encoder.encode(`${entry.path}\\0${entry.content.length}\\0`)",
      "encoder.encode(`${entry.path}\\0${entry.content.length}\\0\\0`)",
    );
    assertEquals(result.code, 1);
    assertStringIncludes(result.stdout.join("\n"), "self-test:");
  });
});

Deno.test("an unknown command is a usage error", async () => {
  const result = await runCli(["frobnicate"]);
  assertEquals(result.code, 2);
  assertEquals(result.stdout, []);
  assertStringIncludes(result.stderr.join("\n"), "frobnicate");
});

Deno.test("naming no command at all is a usage error", async () => {
  const result = await runCli([]);
  assertEquals(result.code, 2);
  assertEquals(result.stdout, []);
});

Deno.test("an unknown option is a usage error", async () => {
  const result = await runCli(["verify", "--depth", "2"]);
  assertEquals(result.code, 2);
  assertEquals(result.stdout, []);
});

Deno.test("--root with no path after it is a usage error", async () => {
  const result = await runCli(["verify", "--root"]);
  assertEquals(result.code, 2);
});

Deno.test("asking for help prints the commands and exits cleanly", async () => {
  const result = await runCli(["--help"]);
  assertEquals(result.code, 0);
  const text = result.stdout.join("\n");
  for (
    const command of [
      "gen",
      "verify",
      "accept",
      "lint-selfcontain",
      "self-test",
    ]
  ) {
    assertStringIncludes(text, command);
  }
});
