import { expect, test } from "bun:test";
import * as fs from "node:fs/promises";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { ConfigError } from "./errors.ts";
import { planExpansion, readContracts } from "./gen.ts";
import {
  escapeThrough,
  kindsOf,
  PERMISSIONS_APPLY,
  readManifest,
  replaceWithSymlink,
  runCli,
  snapshotTree,
  withGoodTree,
  withUnreadable,
  writeFile,
  writeManifest,
} from "./testing.ts";

const COPY = "skills/review-writer/references/vendor/verdict-format.md";
const MANIFEST = "vendor-manifest.json";

test("planning over a declared contract whose text is missing refuses instead of skipping", async () => {
  await withGoodTree(async (root) => {
    // gen and accept refuse this shape before planning; the refusal here is
    // for a future caller that forgets the acceptance check — a plan that
    // silently dropped the contract would write a manifest nobody declared.
    await expect(
      planExpansion(
        root,
        [{ name: "release-notes", contracts: ["changelog-entry"] }],
        new Map([["changelog-entry", null]]),
        {},
      ),
    ).rejects.toThrow(ConfigError);
  });
});

test("a contracts path that is not a directory is refused with the fact named", async () => {
  await withGoodTree(async (root) => {
    // A file standing at contracts/ made every contract below it read as
    // "does not exist" — a claim about the tree that is not true, and a
    // different one from the fact that the directory is not a directory.
    await fs.rm(`${root}/contracts`, { recursive: true });
    await fs.writeFile(`${root}/contracts`, "not a directory");

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    expect(result.stderr.join("\n")).toContain("contracts: not a directory");
  });
});

test("gen leaves an already generated tree byte identical", async () => {
  await withGoodTree(async (root) => {
    const before = await snapshotTree(root);
    const result = await runCli(["gen", "--root", root]);
    expect(result.code, result.stderr.join("\n")).toStrictEqual(0);
    expect(await snapshotTree(root)).toStrictEqual(before);
  });
});

test("generating twice from the same input is byte identical", async () => {
  await withGoodTree(async (root) => {
    await fs.rm(`${root}/${COPY}`);
    expect((await runCli(["gen", "--root", root])).code).toStrictEqual(0);
    const first = await snapshotTree(root);
    expect((await runCli(["gen", "--root", root])).code).toStrictEqual(0);
    expect(await snapshotTree(root)).toStrictEqual(first);
  });
});

test("a vendored copy carries the do-not-edit header, its id and its source digest", async () => {
  await withGoodTree(async (root) => {
    await fs.rm(`${root}/${COPY}`);
    expect((await runCli(["gen", "--root", root])).code).toStrictEqual(0);
    const written = await fs.readFile(`${root}/${COPY}`, "utf8");
    const digest = (await readManifest(root)).lock.resolutions["verdict-format"]
      .digest;
    expect(written.split("\n").slice(0, 4)).toStrictEqual([
      "<!-- DO NOT EDIT. Generated by agentic-skill-vendor. -->",
      "<!-- contract: verdict-format -->",
      `<!-- source-digest: ${digest} -->`,
      "",
    ]);
  });
});

test("a vendored copy holds the canonical contract body", async () => {
  await withGoodTree(async (root) => {
    await fs.rm(`${root}/${COPY}`);
    expect((await runCli(["gen", "--root", root])).code).toStrictEqual(0);
    const written = await fs.readFile(`${root}/${COPY}`, "utf8");
    const source = await fs.readFile(
      `${root}/contracts/verdict-format.md`,
      "utf8",
    );
    expect(written.split("\n").slice(4).join("\n")).toStrictEqual(
      source.slice(source.indexOf("# Verdict Format")),
    );
  });
});

test("gen refuses a contract that has never been accepted and writes nothing", async () => {
  await withGoodTree(async (root) => {
    const manifest = await readManifest(root);
    delete manifest.lock.resolutions["verdict-format"];
    await writeManifest(root, manifest);
    const before = await snapshotTree(root);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(1);
    expect(kindsOf(result.stdout)).toStrictEqual(["unresolved"]);
    expect(await snapshotTree(root)).toStrictEqual(before);
  });
});

test("gen refuses a canonical text that drifted from its resolution and writes nothing", async () => {
  await withGoodTree(async (root) => {
    await fs.writeFile(
      `${root}/contracts/verdict-format.md`,
      (await fs.readFile(`${root}/contracts/verdict-format.md`, "utf8")) +
        "\nOne more rule.\n",
    );
    const before = await snapshotTree(root);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(1);
    expect(kindsOf(result.stdout)).toStrictEqual(["unaccepted-drift"]);
    expect(result.stdout[0]).toContain("verdict-format");
    expect(await snapshotTree(root)).toStrictEqual(before);
  });
});

test("gen refuses a declared contract with no canonical file and writes nothing", async () => {
  await withGoodTree(async (root) => {
    await fs.rm(`${root}/contracts/verdict-format.md`);
    const before = await snapshotTree(root);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(1);
    expect(kindsOf(result.stdout)).toStrictEqual(["closure"]);
    expect(await snapshotTree(root)).toStrictEqual(before);
  });
});

test("gen removes a vendored copy no declaration accounts for", async () => {
  await withGoodTree(async (root) => {
    const orphan = "skills/release-notes/references/vendor/orphan.md";
    await writeFile(`${root}/${orphan}`, "left over from an old declaration\n");

    expect((await runCli(["gen", "--root", root])).code).toStrictEqual(0);
    expect((await snapshotTree(root)).has(orphan)).toStrictEqual(false);
  });
});

test("adding a dependency on an already resolved contract needs no acceptance", async () => {
  await withGoodTree(async (root) => {
    const skill = `${root}/skills/release-notes/SKILL.md`;
    await fs.writeFile(
      skill,
      (await fs.readFile(skill, "utf8")).replace(
        "    - changelog-entry\n",
        "    - changelog-entry\n    - verdict-format\n",
      ),
    );

    const result = await runCli(["gen", "--root", root]);
    expect(
      result.code,
      result.stdout.concat(result.stderr).join("\n"),
    ).toStrictEqual(0);
    expect(
      (await readManifest(root)).lock.dependencies["release-notes"],
    ).toStrictEqual(["changelog-entry", "verdict-format"]);
    expect(
      await fs.readFile(
        `${root}/skills/release-notes/references/vendor/verdict-format.md`,
        "utf8",
      ),
    ).toContain("# Verdict Format");
  });
});

test("gen refuses a skill whose declaration cannot be read and keeps its vendored copies", async () => {
  await withGoodTree(async (root) => {
    const skill = `${root}/skills/review-writer/SKILL.md`;
    await fs.writeFile(
      skill,
      (await fs.readFile(skill, "utf8")).replace(
        "metadata:\n",
        "metadata:\n  audience: internal\nmetadata:\n",
      ),
    );
    const before = await snapshotTree(root);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    expect(result.stderr.join("\n")).toContain("error:");
    expect(await snapshotTree(root)).toStrictEqual(before);
  });
});

test("a dependent skill name with control bytes is quoted in the closure finding", async () => {
  await withGoodTree(async (root) => {
    // The acceptance violation names the skills that declare the contract; a
    // skill name holding an ANSI escape would paint the terminal on the line.
    const name = "esc\u001b[31m";
    await writeFile(
      `${root}/skills/${name}/SKILL.md`,
      "---\nname: esc\nmetadata:\n  contracts:\n    - verdict-format\n---\n\n# esc\n",
    );
    await fs.rm(`${root}/contracts/verdict-format.md`);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(1);
    const closure = result.stdout.find((line) => line.startsWith("closure:"));
    expect(closure).toBeDefined();
    expect(closure).not.toContain("\u001b");
    expect(closure).toContain("\\u001b");
  });
});

test("gen refuses a vendor directory symlinked outside the tree", async () => {
  await withGoodTree(async (root) => {
    const outside = `${root.slice(0, root.lastIndexOf("/"))}/outside`;
    await fs.mkdir(outside, { recursive: true });
    await replaceWithSymlink(
      `${root}/skills/release-notes/references/vendor`,
      outside,
    );
    const outsideBefore = await snapshotTree(outside);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    expect(result.stderr.join("\n")).toContain("error:");
    expect(await snapshotTree(outside)).toStrictEqual(outsideBefore);
  });
});

test("gen refuses a symlink planted at the manifest temporary path", async () => {
  await withGoodTree(async (root) => {
    const outside = `${root.slice(0, root.lastIndexOf("/"))}/outside`;
    await writeFile(`${outside}/target.json`, "must not be overwritten\n");
    await fs.rm(`${root}/${COPY}`);
    await replaceWithSymlink(
      `${root}/${MANIFEST}.tmp`,
      `${outside}/target.json`,
    );

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    expect(await fs.readFile(`${outside}/target.json`, "utf8")).toStrictEqual(
      "must not be overwritten\n",
    );
  });
});

test("gen exits 2 naming the path when a vendored copy cannot be written", async () => {
  await withGoodTree(async (root) => {
    await fs.rm(`${root}/${COPY}`);
    await fs.mkdir(`${root}/${COPY}`);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    expect(result.stderr.join("\n")).toContain("verdict-format.md");
  });
});

test("a run interrupted by an unwritable copy leaves every other file in place", async () => {
  await withGoodTree(async (root) => {
    const blocked = "skills/review-writer/references/vendor/changelog-entry.md";
    await fs.rm(`${root}/${blocked}`);
    await fs.mkdir(`${root}/${blocked}`);

    expect((await runCli(["gen", "--root", root])).code).toStrictEqual(2);
    const after = await snapshotTree(root);
    expect(after.has(COPY)).toStrictEqual(true);
    expect(after.has(MANIFEST)).toStrictEqual(true);
    expect(
      after.has("skills/release-notes/references/vendor/changelog-entry.md"),
    ).toStrictEqual(true);
  });
});

// The five shapes a planted link can take on the way to the text this tool
// reads. They are stated together because each is reached through a different
// primitive, so a guard proven on one says nothing about the other four — and
// two of them were open while the other three were closed.
//
// A directory link is the dangerous half: every path below it resolves outside
// the boundary the run was pointed at, so the run reads outside text, pins its
// digest, and writes it into the tree while reporting nothing.

test("gen refuses a contracts directory symlinked outside the tree", async () => {
  await withGoodTree(async (root) => {
    const outside = await escapeThrough(root, "contracts");
    // The moved text is edited before the run, so that following the link and
    // refusing it are two different answers: read through the link, the edit is
    // unaccepted drift reported on standard output with exit 1. Left byte
    // identical it would instead reach exit 2 by another route — the same
    // refusal raised while the manifest's provenance is built — and this case
    // would go on passing with the refusal it names taken out.
    const escaped = `${outside}/contracts/verdict-format.md`;
    await fs.writeFile(
      escaped,
      (await fs.readFile(escaped, "utf8")) + "\nOne more rule.\n",
    );
    const outsideBefore = await snapshotTree(outside);
    const treeBefore = await snapshotTree(root);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    // Named as the directory itself: readContracts asks what stands at
    // contracts/ once, before any contract below it is looked up, so the
    // refusal quotes the link the run was pointed at rather than whichever
    // file happened to be reached through it.
    expect(result.stderr.join("\n")).toContain(
      "symlink is not allowed inside the tree: contracts",
    );
    expect(result.stderr.join("\n")).not.toMatch(
      /symlink is not allowed inside the tree: contracts\/[^\s]+\.md/,
    );
    expect(await snapshotTree(outside)).toStrictEqual(outsideBefore);
    expect(await snapshotTree(root)).toStrictEqual(treeBefore);
  });
});

test("accept refuses a contracts directory symlinked outside the tree", async () => {
  await withGoodTree(async (root) => {
    const outside = await escapeThrough(root, "contracts");
    const outsideBefore = await snapshotTree(outside);
    const treeBefore = await snapshotTree(root);

    const result = await runCli(["accept", "verdict-format", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    expect(result.stderr.join("\n")).toContain(
      "symlink is not allowed inside the tree: contracts",
    );
    expect(await snapshotTree(outside)).toStrictEqual(outsideBefore);
    expect(await snapshotTree(root)).toStrictEqual(treeBefore);
  });
});

test("verify refuses a contracts directory symlinked outside the tree", async () => {
  await withGoodTree(async (root) => {
    await escapeThrough(root, "contracts");
    const result = await runCli(["verify", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
  });
});

test("gen and verify both refuse a contract's own directory symlinked outside the tree", async () => {
  await withGoodTree(async (root) => {
    // A link at the directory a contract's conformance tests live in. Only
    // verify ever reads through that directory, so the two commands used to
    // answer the same planted link differently: verify stopped, gen expanded
    // the tree and said nothing. Whether a link is refused is a fact about the
    // tree, so it cannot depend on which command is looking.
    const outside = await escapeThrough(root, "contracts/changelog-entry");
    const outsideBefore = await snapshotTree(outside);
    const treeBefore = await snapshotTree(root);

    for (const command of ["gen", "verify"]) {
      const result = await runCli([command, "--root", root]);
      expect(result.code, command).toStrictEqual(2);
      expect(result.stdout, command).toStrictEqual([]);
      expect(result.stderr.join("\n"), command).toContain(
        "symlink is not allowed inside the tree: contracts/changelog-entry",
      );
    }
    expect(await snapshotTree(outside)).toStrictEqual(outsideBefore);
    expect(await snapshotTree(root)).toStrictEqual(treeBefore);
  });
});

test("a contract's own directory symlinked outside the tree is refused before what the lock lacks is reported", async () => {
  await withGoodTree(async (root) => {
    // The link stands where a violation would otherwise be reported: with the
    // resolution dropped, the contract reads as unresolved, which is a fact
    // about the tree stated on standard output with exit 1. A planted link is
    // not that. The run could not find out what the tree says, so it stops
    // before it has anything to report — and it stops here, on the way to the
    // canonical text, rather than later while provenance is built, which is
    // never reached once a violation has been found.
    const manifest = await readManifest(root);
    delete manifest.lock.resolutions["changelog-entry"];
    await writeManifest(root, manifest);
    const outside = await escapeThrough(root, "contracts/changelog-entry");
    const outsideBefore = await snapshotTree(outside);
    const treeBefore = await snapshotTree(root);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    expect(result.stderr.join("\n")).toContain(
      "symlink is not allowed inside the tree: contracts/changelog-entry",
    );
    expect(await snapshotTree(outside)).toStrictEqual(outsideBefore);
    expect(await snapshotTree(root)).toStrictEqual(treeBefore);
  });
});

test("accept refuses a contract file symlinked outside the tree", async () => {
  await withGoodTree(async (root) => {
    const outside = await escapeThrough(root, "contracts/verdict-format.md");
    const outsideBefore = await snapshotTree(outside);

    const result = await runCli(["accept", "verdict-format", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    expect(await snapshotTree(outside)).toStrictEqual(outsideBefore);
  });
});

test("every command reading contracts refuses a conformance directory symlinked outside the tree", async () => {
  await withGoodTree(async (root) => {
    // The deepest of the directory shapes, and the one that used to answer
    // three ways: verify digests the tests below it and stopped, accepting
    // this contract stopped, and gen — which never reads them — expanded the
    // tree, as did accepting any other contract.
    const outside = await escapeThrough(
      root,
      "contracts/changelog-entry/conformance",
    );
    const outsideBefore = await snapshotTree(outside);
    const treeBefore = await snapshotTree(root);

    for (const command of [["gen"], ["verify"], ["accept", "verdict-format"]]) {
      const result = await runCli([...command, "--root", root]);
      expect(result.code, command[0]).toStrictEqual(2);
      expect(result.stdout, command[0]).toStrictEqual([]);
      expect(result.stderr.join("\n"), command[0]).toContain(
        "symlink is not allowed inside the tree: contracts/changelog-entry/conformance",
      );
    }
    expect(await snapshotTree(outside)).toStrictEqual(outsideBefore);
    expect(await snapshotTree(root)).toStrictEqual(treeBefore);
  });
});

test("verify refuses a skills directory symlinked outside the tree", async () => {
  await withGoodTree(async (root) => {
    const outside = await escapeThrough(root, "skills");
    const outsideBefore = await snapshotTree(outside);

    const result = await runCli(["verify", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    expect(await snapshotTree(outside)).toStrictEqual(outsideBefore);
  });
});

test("gen refuses a skill directory that is itself a symlink", async () => {
  await withGoodTree(async (root) => {
    // Read as an ordinary entry the link is not a directory, so the skill drops
    // out of the list without a word: its declarations stop being seen and its
    // dependency edge leaves the lock. Refusing is what keeps that silent.
    await escapeThrough(root, "skills/release-notes");

    const result = await runCli(["verify", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    expect(result.stderr.join("\n")).toContain(
      "symlink is not allowed inside the tree: skills/release-notes",
    );
  });
});

test("gen refuses a symlink standing among a skill's vendored copies", async () => {
  await withGoodTree(async (root) => {
    // Treated as an ordinary name it answers to no declaration, so the run
    // would quietly delete it as an unaccounted copy.
    const link = "skills/release-notes/references/vendor/orphan.md";
    await replaceWithSymlink(`${root}/${link}`, `${root}/${COPY}`);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    expect(result.stderr.join("\n")).toContain(
      `symlink is not allowed inside the tree: ${link}`,
    );
  });
});

test("gen refuses a vendor directory reached through a symlinked parent", async () => {
  await withGoodTree(async (root) => {
    // The link is one level above the vendor directory, so checking only the
    // directory itself finds a plain directory and reports nothing — while
    // every copy written and every stray removed lands outside the tree.
    const outside = `${root.slice(0, root.lastIndexOf("/"))}/outside`;
    await writeFile(`${outside}/references/vendor/stray.md`, "not ours\n");
    await replaceWithSymlink(
      `${root}/skills/release-notes/references`,
      `${outside}/references`,
    );
    const outsideBefore = await snapshotTree(outside);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    expect(result.stderr.join("\n")).toContain(
      "symlink is not allowed inside the tree: skills/release-notes/references/vendor",
    );
    expect(await snapshotTree(outside)).toStrictEqual(outsideBefore);
  });
});

test("gen refuses a manifest symlinked outside the tree before reading it", async () => {
  await withGoodTree(async (root) => {
    // Refused where it is read, not merely where it is written. Left to the
    // write, the run would first adopt an outside lock and expand the whole
    // tree from it, and only then stop.
    const outside = `${root.slice(0, root.lastIndexOf("/"))}/outside`;
    await fs.mkdir(outside, { recursive: true });
    await fs.rename(`${root}/${MANIFEST}`, `${outside}/${MANIFEST}`);
    await fs.symlink(`${outside}/${MANIFEST}`, `${root}/${MANIFEST}`);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    expect(result.stderr.join("\n")).toContain(
      `symlink is not allowed inside the tree: ${MANIFEST}`,
    );
  });
});

test("a run stopped by an unwritable copy has removed nothing and rewritten no lock", async () => {
  await withGoodTree(async (root) => {
    // Copies, then the manifest, then the removals. The order is what decides
    // what an interrupted run leaves: a removal done first would lose a file
    // the run never replaced, and a manifest written first would describe a
    // tree that was never built.
    const orphan = "skills/release-notes/references/vendor/orphan.md";
    await writeFile(`${root}/${orphan}`, "left over from an old declaration\n");
    const skill = `${root}/skills/release-notes/SKILL.md`;
    await fs.writeFile(
      skill,
      (await fs.readFile(skill, "utf8")).replace(
        "    - changelog-entry\n",
        "    - changelog-entry\n    - verdict-format\n",
      ),
    );
    const blocked = "skills/review-writer/references/vendor/changelog-entry.md";
    await fs.rm(`${root}/${blocked}`);
    await fs.mkdir(`${root}/${blocked}`);
    const manifestBefore = await fs.readFile(`${root}/${MANIFEST}`, "utf8");

    expect((await runCli(["gen", "--root", root])).code).toStrictEqual(2);
    expect((await snapshotTree(root)).has(orphan)).toStrictEqual(true);
    expect(await fs.readFile(`${root}/${MANIFEST}`, "utf8")).toStrictEqual(
      manifestBefore,
    );
  });
});

test("gen refuses a skill whose opening delimiter is not exactly the delimiter and keeps its vendored copies", async () => {
  await withGoodTree(async (root) => {
    const skill = `${root}/skills/release-notes/SKILL.md`;
    const lines = (await fs.readFile(skill, "utf8")).split("\n");
    lines[0] = "--- ";
    await fs.writeFile(skill, lines.join("\n"));
    const before = await snapshotTree(root);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    expect(await snapshotTree(root)).toStrictEqual(before);
  });
});

test("gen refuses a skill whose opening delimiter carries a zero-width character and keeps its vendored copies", async () => {
  await withGoodTree(async (root) => {
    const skill = `${root}/skills/release-notes/SKILL.md`;
    const lines = (await fs.readFile(skill, "utf8")).split("\n");
    lines[0] = "\u200b---";
    await fs.writeFile(skill, lines.join("\n"));
    const before = await snapshotTree(root);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    expect(await snapshotTree(root)).toStrictEqual(before);
  });
});

test("gen refuses a skill reaching its opening delimiter only after a blank line and keeps its vendored copies", async () => {
  await withGoodTree(async (root) => {
    const skill = `${root}/skills/release-notes/SKILL.md`;
    await fs.writeFile(skill, "\n" + (await fs.readFile(skill, "utf8")));
    const before = await snapshotTree(root);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    expect(await snapshotTree(root)).toStrictEqual(before);
  });
});

const describeRemoval = PERMISSIONS_APPLY ? test : test.skip;

describeRemoval(
  "gen refuses a stale vendored copy it could not remove, having written everything else",
  async () => {
    await withGoodTree(async (root) => {
      // The removals run last, so a failure here finds every copy and the lock
      // already in place: what is left over is the one thing the run could not
      // clear. Passed over in silence, gen answered 0 while verify reported the
      // leftover as an extra — and running gen again changed neither answer, so
      // the two commands disagreed for as long as the tree stayed that way.
      const orphan = "skills/release-notes/references/vendor/orphan.md";
      await writeFile(`${root}/${orphan}/inside.md`, "blocks the removal\n");
      await fs.rm(`${root}/${COPY}`);

      await withUnreadable(`${root}/${orphan}`, async () => {
        const result = await runCli(["gen", "--root", root]);
        expect(result.code).toStrictEqual(2);
        expect(result.stdout).toStrictEqual([]);
        expect(result.stderr.join("\n")).toContain(orphan);
      });

      // What the run did finish is still there: the copy deleted above was
      // written back before the removals were attempted.
      expect(await fs.readFile(`${root}/${COPY}`, "utf8")).toContain(
        "# Verdict Format",
      );
    });
  },
);

test("every command refuses a declared contract whose canonical text is not a regular file", async () => {
  await withGoodTree(async (root) => {
    // The same shape one step earlier, where a declaration still names the
    // contract. Text that is not there at all is a closure gap — a fact about
    // the tree, reported with exit 1. A directory standing where the text
    // belongs is not that fact: the run cannot find out what the contract says,
    // which is what separates a report from a refusal.
    await fs.rm(`${root}/contracts/verdict-format.md`);
    await fs.mkdir(`${root}/contracts/verdict-format.md`);
    const before = await snapshotTree(root);

    for (const command of [
      ["gen"],
      ["verify"],
      ["accept", "changelog-entry"],
    ]) {
      const result = await runCli([...command, "--root", root]);
      expect(result.code, command[0]).toStrictEqual(2);
      expect(result.stdout, command[0]).toStrictEqual([]);
      expect(result.stderr.join("\n"), command[0]).toContain(
        "contracts/verdict-format.md: not a regular file",
      );
    }
    expect(await snapshotTree(root)).toStrictEqual(before);
  });
});

// Every path the run writes through, blocked by something it must not open.
// A named pipe passes the check for links — it is not one — and the open then
// waits for a reader that never comes. The tests carry their own deadline so a
// regression fails in seconds instead of stopping the suite for good.

const WRITE_TARGETS = [
  "skills/review-writer/references/vendor/verdict-format.md",
  "skills/review-writer/references/vendor/verdict-format.md.tmp",
  `${MANIFEST}.tmp`,
];

test("gen and accept refuse a named pipe standing where the run would write", async () => {
  for (const site of WRITE_TARGETS) {
    for (const command of [["gen"], ["accept", "changelog-entry"]]) {
      await withGoodTree(async (root) => {
        await fs.rm(`${root}/${site}`).catch(() => {});
        await promisify(execFile)("mkfifo", [`${root}/${site}`]);

        const where = `${site} / ${command[0]}`;
        const result = await runCli([...command, "--root", root]);
        expect(result.code, where).toStrictEqual(2);
        expect(result.stderr.join("\n"), where).toContain(site);
        // Left as it was found: refusing is not a licence to clear the path.
        expect(
          (await fs.lstat(`${root}/${site}`)).isFIFO(),
          where,
        ).toStrictEqual(true);
      });
    }
  }
}, 15000);

test("a contract named for an inherited property is reported as unresolved, not as drift against nothing", async () => {
  await withGoodTree(async (root) => {
    // `constructor` is a usable contract id, and looking it up in a plain
    // object finds Object's own constructor rather than nothing. The run then
    // reads a resolution that was never recorded, and says the text drifted
    // from a digest of `undefined` instead of saying it was never accepted.
    await fs.copyFile(
      `${root}/contracts/verdict-format.md`,
      `${root}/contracts/constructor.md`,
    );
    const skill = `${root}/skills/release-notes/SKILL.md`;
    await fs.writeFile(
      skill,
      (await fs.readFile(skill, "utf8")).replace(
        "    - changelog-entry\n",
        "    - changelog-entry\n    - constructor\n",
      ),
    );

    // Asked of every command that reads the lock, including the one that
    // works from its own copy of it. The first finding reported is the
    // acceptance one: the acceptance check runs before the file-system checks
    // in every command, so the run says the contract was never accepted before
    // it says anything about how the state drifted.
    for (const command of [
      ["gen"],
      ["verify"],
      ["accept", "changelog-entry"],
    ]) {
      const result = await runCli([...command, "--root", root]);
      expect(result.code, command[0]).toStrictEqual(1);
      expect(kindsOf(result.stdout), command[0]).toContain("unresolved");
      expect(result.stdout[0], command[0]).toContain("constructor");
      expect(result.stdout[0].startsWith("unresolved:"), command[0]).toBe(true);
    }
  });
});

// The same inherited-property read, on the two paths that answer "nothing is
// resolved yet" rather than reading recorded resolutions: a tree with no
// manifest at all, and a lock whose recorded resolutions are empty. Both are
// what a repository adopting this tool starts from.

const EMPTY_LOCK_SHAPES: {
  what: string;
  write: (root: string) => Promise<void>;
}[] = [
  {
    what: "no manifest at all",
    write: async (root) => await fs.rm(`${root}/${MANIFEST}`),
  },
  {
    what: "a lock recording no resolutions",
    write: async (root) =>
      await fs.writeFile(
        `${root}/${MANIFEST}`,
        '{"lock":{"dependencies":{"release-notes":["changelog-entry","constructor"]},"resolutions":{}}}\n',
      ),
  },
];

test("a contract named for an inherited property is unresolved on a tree that has resolved nothing", async () => {
  for (const { what, write } of EMPTY_LOCK_SHAPES) {
    await withGoodTree(async (root) => {
      await fs.copyFile(
        `${root}/contracts/verdict-format.md`,
        `${root}/contracts/constructor.md`,
      );
      const skill = `${root}/skills/release-notes/SKILL.md`;
      await fs.writeFile(
        skill,
        (await fs.readFile(skill, "utf8")).replace(
          "    - changelog-entry\n",
          "    - changelog-entry\n    - constructor\n",
        ),
      );
      await write(root);

      for (const command of ["gen", "verify"]) {
        const where = `${what} / ${command}`;
        const result = await runCli([command, "--root", root]);
        const line = result.stdout.find((entry) =>
          entry.includes("constructor"),
        );
        expect(line, where).toBeDefined();
        expect(line?.startsWith("unresolved:"), `${where}: ${line}`).toBe(true);
      }
    });
  }
});

test("a removed canonical text with its declaration left behind keeps its resolution", async () => {
  await withGoodTree(async (root) => {
    // The skill still declares the contract, so gen stops on the closure gap
    // and never reaches the plan that would prune the resolution: only a
    // withdrawal — declaration removed too — retires it.
    await fs.rm(`${root}/contracts/verdict-format.md`);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(1);
    expect(result.stdout.join("\n")).toContain("closure");
    expect(
      "verdict-format" in (await readManifest(root)).lock.resolutions,
    ).toStrictEqual(true);
  });
});

test("a version quoted with a ' #' inside is read whole, not cut at the hash", async () => {
  await withGoodTree(async (root) => {
    // The version is display-only, so a hash inside a quoted value must not
    // read as the start of a comment: a value that says `a # b` means the
    // author wrote the hash as part of the text.
    await fs.writeFile(
      `${root}/contracts/verdict-format.md`,
      '---\nversion: "a # b"\n---\n\nBody\n',
    );
    const contracts = await readContracts(root, ["verdict-format"]);
    expect(contracts.get("verdict-format")?.version).toStrictEqual("a # b");
  });
});

test("a version written bare with a comment is read without the comment", async () => {
  await withGoodTree(async (root) => {
    // Outside quotes a hash does start a comment, and the value left behind is
    // trimmed: `version: 1.2.0 # released in June` names the version as 1.2.0.
    await fs.writeFile(
      `${root}/contracts/verdict-format.md`,
      "---\nversion: 1.2.0 # released in June\n---\n\nBody\n",
    );
    const contracts = await readContracts(root, ["verdict-format"]);
    expect(contracts.get("verdict-format")?.version).toStrictEqual("1.2.0");
  });
});

test("a version written without a space after the colon is read", async () => {
  await withGoodTree(async (root) => {
    // `version:1.2.0` is valid YAML and reads the same as `version: 1.2.0`;
    // the scanner must not demand the space the YAML grammar does not.
    await fs.writeFile(
      `${root}/contracts/verdict-format.md`,
      "---\nversion:1.2.0\n---\n\nBody\n",
    );
    const contracts = await readContracts(root, ["verdict-format"]);
    expect(contracts.get("verdict-format")?.version).toStrictEqual("1.2.0");
  });
});
