import { expect, test } from "bun:test";
import * as fs from "node:fs/promises";
import {
  replaceWithSymlink,
  runCli,
  snapshotTree,
  withGoodTree,
  writeFile,
} from "./testing.ts";

const COPY = "skills/review-writer/references/vendor/verdict-format.md";
const MANIFEST = "vendor-manifest.json";

// deno-lint-ignore no-explicit-any
type Json = any;

async function readManifest(root: string): Promise<Json> {
  return JSON.parse(await fs.readFile(`${root}/${MANIFEST}`, "utf8"));
}

async function writeManifest(root: string, manifest: Json): Promise<void> {
  await fs.writeFile(
    `${root}/${MANIFEST}`,
    JSON.stringify(manifest, null, 2) + "\n",
  );
}

function kindsOf(lines: string[]): string[] {
  return lines.map((line) => line.slice(0, line.indexOf(":")));
}

test("gen leaves an already generated tree byte identical", async () => {
  await withGoodTree(async (root) => {
    const before = await snapshotTree(root);
    const result = await runCli(["gen", "--root", root]);
    expect(result.code, result.stderr.join("\n")).toStrictEqual(0);
    expect(await snapshotTree(root)).toStrictEqual(before);
  });
});

test("generating twice from the same input is byte identical", async () => {
  await withGoodTree(async (root) => {
    await fs.rm(`${root}/${COPY}`);
    expect((await runCli(["gen", "--root", root])).code).toStrictEqual(0);
    const first = await snapshotTree(root);
    expect((await runCli(["gen", "--root", root])).code).toStrictEqual(0);
    expect(await snapshotTree(root)).toStrictEqual(first);
  });
});

test("a vendored copy carries the do-not-edit header, its id and its source digest", async () => {
  await withGoodTree(async (root) => {
    await fs.rm(`${root}/${COPY}`);
    expect((await runCli(["gen", "--root", root])).code).toStrictEqual(0);
    const written = await fs.readFile(`${root}/${COPY}`, "utf8");
    const digest = (await readManifest(root)).lock.resolutions["verdict-format"]
      .digest;
    expect(written.split("\n").slice(0, 4)).toStrictEqual([
      "<!-- DO NOT EDIT. Generated by vendor.ts. -->",
      "<!-- contract: verdict-format -->",
      `<!-- source-digest: ${digest} -->`,
      "",
    ]);
  });
});

test("a vendored copy holds the canonical contract body", async () => {
  await withGoodTree(async (root) => {
    await fs.rm(`${root}/${COPY}`);
    expect((await runCli(["gen", "--root", root])).code).toStrictEqual(0);
    const written = await fs.readFile(`${root}/${COPY}`, "utf8");
    const source = await fs.readFile(
      `${root}/contracts/verdict-format.md`,
      "utf8",
    );
    expect(written.split("\n").slice(4).join("\n")).toStrictEqual(
      source.slice(source.indexOf("# Verdict Format")),
    );
  });
});

test("gen refuses a contract that has never been accepted and writes nothing", async () => {
  await withGoodTree(async (root) => {
    const manifest = await readManifest(root);
    delete manifest.lock.resolutions["verdict-format"];
    await writeManifest(root, manifest);
    const before = await snapshotTree(root);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(1);
    expect(kindsOf(result.stdout)).toStrictEqual(["unresolved"]);
    expect(await snapshotTree(root)).toStrictEqual(before);
  });
});

test("gen refuses a canonical text that drifted from its resolution and writes nothing", async () => {
  await withGoodTree(async (root) => {
    await fs.writeFile(
      `${root}/contracts/verdict-format.md`,
      (await fs.readFile(`${root}/contracts/verdict-format.md`, "utf8")) +
        "\nOne more rule.\n",
    );
    const before = await snapshotTree(root);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(1);
    expect(kindsOf(result.stdout)).toStrictEqual(["unaccepted-drift"]);
    expect(result.stdout[0]).toContain("verdict-format");
    expect(await snapshotTree(root)).toStrictEqual(before);
  });
});

test("gen refuses a declared contract with no canonical file and writes nothing", async () => {
  await withGoodTree(async (root) => {
    await fs.rm(`${root}/contracts/verdict-format.md`);
    const before = await snapshotTree(root);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(1);
    expect(kindsOf(result.stdout)).toStrictEqual(["closure"]);
    expect(await snapshotTree(root)).toStrictEqual(before);
  });
});

test("gen removes a vendored copy no declaration accounts for", async () => {
  await withGoodTree(async (root) => {
    const orphan = "skills/release-notes/references/vendor/orphan.md";
    await writeFile(`${root}/${orphan}`, "left over from an old declaration\n");

    expect((await runCli(["gen", "--root", root])).code).toStrictEqual(0);
    expect((await snapshotTree(root)).has(orphan)).toStrictEqual(false);
  });
});

test("adding a dependency on an already resolved contract needs no acceptance", async () => {
  await withGoodTree(async (root) => {
    const skill = `${root}/skills/release-notes/SKILL.md`;
    await fs.writeFile(
      skill,
      (await fs.readFile(skill, "utf8")).replace(
        "    - changelog-entry\n",
        "    - changelog-entry\n    - verdict-format\n",
      ),
    );

    const result = await runCli(["gen", "--root", root]);
    expect(
      result.code,
      result.stdout.concat(result.stderr).join("\n"),
    ).toStrictEqual(0);
    expect(
      (await readManifest(root)).lock.dependencies["release-notes"],
    ).toStrictEqual(["changelog-entry", "verdict-format"]);
    expect(
      await fs.readFile(
        `${root}/skills/release-notes/references/vendor/verdict-format.md`,
        "utf8",
      ),
    ).toContain("# Verdict Format");
  });
});

test("gen refuses a skill whose declaration cannot be read and keeps its vendored copies", async () => {
  await withGoodTree(async (root) => {
    const skill = `${root}/skills/review-writer/SKILL.md`;
    await fs.writeFile(
      skill,
      (await fs.readFile(skill, "utf8")).replace(
        "metadata:\n",
        "metadata:\n  audience: internal\nmetadata:\n",
      ),
    );
    const before = await snapshotTree(root);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    expect(result.stderr.join("\n")).toContain("error:");
    expect(await snapshotTree(root)).toStrictEqual(before);
  });
});

test("gen refuses a vendor directory symlinked outside the tree", async () => {
  await withGoodTree(async (root) => {
    const outside = `${root.slice(0, root.lastIndexOf("/"))}/outside`;
    await fs.mkdir(outside, { recursive: true });
    await replaceWithSymlink(
      `${root}/skills/release-notes/references/vendor`,
      outside,
    );
    const outsideBefore = await snapshotTree(outside);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    expect(result.stderr.join("\n")).toContain("error:");
    expect(await snapshotTree(outside)).toStrictEqual(outsideBefore);
  });
});

test("gen refuses a symlink planted at the manifest temporary path", async () => {
  await withGoodTree(async (root) => {
    const outside = `${root.slice(0, root.lastIndexOf("/"))}/outside`;
    await writeFile(`${outside}/target.json`, "must not be overwritten\n");
    await fs.rm(`${root}/${COPY}`);
    await replaceWithSymlink(
      `${root}/${MANIFEST}.tmp`,
      `${outside}/target.json`,
    );

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    expect(await fs.readFile(`${outside}/target.json`, "utf8")).toStrictEqual(
      "must not be overwritten\n",
    );
  });
});

test("gen exits 2 naming the path when a vendored copy cannot be written", async () => {
  await withGoodTree(async (root) => {
    await fs.rm(`${root}/${COPY}`);
    await fs.mkdir(`${root}/${COPY}`);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    expect(result.stderr.join("\n")).toContain("verdict-format.md");
  });
});

test("a run interrupted by an unwritable copy leaves every other file in place", async () => {
  await withGoodTree(async (root) => {
    const blocked = "skills/review-writer/references/vendor/changelog-entry.md";
    await fs.rm(`${root}/${blocked}`);
    await fs.mkdir(`${root}/${blocked}`);

    expect((await runCli(["gen", "--root", root])).code).toStrictEqual(2);
    const after = await snapshotTree(root);
    expect(after.has(COPY)).toStrictEqual(true);
    expect(after.has(MANIFEST)).toStrictEqual(true);
    expect(
      after.has("skills/release-notes/references/vendor/changelog-entry.md"),
    ).toStrictEqual(true);
  });
});

test("gen refuses a skill whose opening delimiter is not exactly the delimiter and keeps its vendored copies", async () => {
  await withGoodTree(async (root) => {
    const skill = `${root}/skills/release-notes/SKILL.md`;
    const lines = (await fs.readFile(skill, "utf8")).split("\n");
    lines[0] = "--- ";
    await fs.writeFile(skill, lines.join("\n"));
    const before = await snapshotTree(root);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    expect(await snapshotTree(root)).toStrictEqual(before);
  });
});

test("gen refuses a skill whose opening delimiter carries a zero-width character and keeps its vendored copies", async () => {
  await withGoodTree(async (root) => {
    const skill = `${root}/skills/release-notes/SKILL.md`;
    const lines = (await fs.readFile(skill, "utf8")).split("\n");
    lines[0] = "\u200b---";
    await fs.writeFile(skill, lines.join("\n"));
    const before = await snapshotTree(root);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    expect(await snapshotTree(root)).toStrictEqual(before);
  });
});

test("gen refuses a skill reaching its opening delimiter only after a blank line and keeps its vendored copies", async () => {
  await withGoodTree(async (root) => {
    const skill = `${root}/skills/release-notes/SKILL.md`;
    await fs.writeFile(skill, "\n" + (await fs.readFile(skill, "utf8")));
    const before = await snapshotTree(root);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    expect(await snapshotTree(root)).toStrictEqual(before);
  });
});
