import { expect, test } from "bun:test";
import * as fs from "node:fs/promises";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { ConfigError } from "./errors.ts";
import { planExpansion } from "./gen.ts";
import {
  append,
  escapeThrough,
  kindsOf,
  PERMISSIONS_APPLY,
  readLockFile,
  replaceWithSymlink,
  runCli,
  snapshotTree,
  withGoodTree,
  withUnreadable,
  writeFile,
  writeLockFile,
} from "./testing.ts";

const COPY = "skills/review-writer/references/vendor/verdict-format.md";
const LOCK = "vendor-lock.json";

test("planning over a declared contract whose text is missing refuses instead of skipping", async () => {
  await withGoodTree(async (root) => {
    // gen refuses this shape before planning; the refusal here is for a
    // future caller that forgets the closure check — a plan that
    // silently dropped the contract would write a lock nobody declared.
    await expect(
      planExpansion(
        root,
        [{ name: "release-notes", contracts: ["changelog-entry"] }],
        new Map([["changelog-entry", null]]),
        {},
        {},
      ),
    ).rejects.toThrow(ConfigError);
  });
});

test("a contracts path that is not a directory is refused with the fact named", async () => {
  await withGoodTree(async (root) => {
    // A file standing at contracts/ made every contract below it read as
    // "does not exist" — a claim about the tree that is not true, and a
    // different one from the fact that the directory is not a directory.
    await fs.rm(`${root}/contracts`, { recursive: true });
    await fs.writeFile(`${root}/contracts`, "not a directory");

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    expect(result.stderr.join("\n")).toContain("contracts: not a directory");
  });
});

test("gen leaves an already generated tree byte identical", async () => {
  await withGoodTree(async (root) => {
    const before = await snapshotTree(root);
    const result = await runCli(["gen", "--root", root]);
    expect(result.code, result.stderr.join("\n")).toStrictEqual(0);
    expect(await snapshotTree(root)).toStrictEqual(before);
  });
});

test("generating twice from the same input is byte identical", async () => {
  await withGoodTree(async (root) => {
    await fs.rm(`${root}/${COPY}`);
    expect((await runCli(["gen", "--root", root])).code).toStrictEqual(0);
    const first = await snapshotTree(root);
    expect((await runCli(["gen", "--root", root])).code).toStrictEqual(0);
    expect(await snapshotTree(root)).toStrictEqual(first);
  });
});

test("a vendored copy carries the do-not-edit header, its id and its source digest", async () => {
  await withGoodTree(async (root) => {
    await fs.rm(`${root}/${COPY}`);
    expect((await runCli(["gen", "--root", root])).code).toStrictEqual(0);
    const written = await fs.readFile(`${root}/${COPY}`, "utf8");
    const digest = (await readLockFile(root)).resolutions["verdict-format"]
      .digest;
    expect(written.split("\n").slice(0, 4)).toStrictEqual([
      "<!-- DO NOT EDIT. Generated by agentic-skill-vendor. -->",
      "<!-- contract: verdict-format -->",
      `<!-- source-digest: ${digest} -->`,
      "",
    ]);
  });
});

test("a vendored copy holds the canonical contract body", async () => {
  await withGoodTree(async (root) => {
    await fs.rm(`${root}/${COPY}`);
    expect((await runCli(["gen", "--root", root])).code).toStrictEqual(0);
    const written = await fs.readFile(`${root}/${COPY}`, "utf8");
    const source = await fs.readFile(
      `${root}/contracts/verdict-format.md`,
      "utf8",
    );
    expect(written.split("\n").slice(4).join("\n")).toStrictEqual(
      source.slice(source.indexOf("# Verdict Format")),
    );
  });
});

test("gen records a contract the lock says nothing about", async () => {
  await withGoodTree(async (root) => {
    const lock = await readLockFile(root);
    const dropped = lock.resolutions["verdict-format"];
    delete lock.resolutions["verdict-format"];
    await writeLockFile(root, lock);

    const result = await runCli(["gen", "--root", root]);
    expect(
      result.code,
      result.stdout.concat(result.stderr).join("\n"),
    ).toStrictEqual(0);
    expect(
      (await readLockFile(root)).resolutions["verdict-format"],
    ).toStrictEqual(dropped);
    expect((await runCli(["verify", "--root", root])).code).toStrictEqual(0);
  });
});

test("gen reports a contract it records for the first time without an old digest", async () => {
  await withGoodTree(async (root) => {
    const lock = await readLockFile(root);
    const digest = lock.resolutions["verdict-format"].digest;
    delete lock.resolutions["verdict-format"];
    await writeLockFile(root, lock);

    const result = await runCli(["gen", "--root", root]);
    expect(result.stdout).toContain(
      `adopted: verdict-format ${digest} (initial adoption)`,
    );
  });
});

test("gen rewrites the lock to the canonical text a contract now holds", async () => {
  await withGoodTree(async (root) => {
    const before = (await readLockFile(root)).resolutions["verdict-format"]
      .digest;
    await append(`${root}/contracts/verdict-format.md`, "\nOne more rule.\n");

    const result = await runCli(["gen", "--root", root]);
    expect(
      result.code,
      result.stdout.concat(result.stderr).join("\n"),
    ).toStrictEqual(0);
    const after = (await readLockFile(root)).resolutions["verdict-format"]
      .digest;
    expect(after).toMatch(/^sha256:[0-9a-f]{64}$/);
    expect(after === before).toStrictEqual(false);
    expect((await runCli(["verify", "--root", root])).code).toStrictEqual(0);
  });
});

test("gen reports both digests when it replaces what a contract was recorded as", async () => {
  await withGoodTree(async (root) => {
    // The line a pull request carries, and the join a consuming repository's
    // regression machinery matches its evidence against: a pass or fail on its
    // own cannot tell adopting this text from adopting a third version.
    const before = (await readLockFile(root)).resolutions["verdict-format"]
      .digest;
    await append(`${root}/contracts/verdict-format.md`, "\nOne more rule.\n");

    const result = await runCli(["gen", "--root", root]);
    const after = (await readLockFile(root)).resolutions["verdict-format"]
      .digest;
    expect(result.stdout).toContain(
      `adopted: verdict-format ${before} -> ${after}`,
    );
  });
});

test("gen over a tree that already matches its lock reports nothing", async () => {
  await withGoodTree(async (root) => {
    // The report names what changed, so a run that changed nothing has nothing
    // to say. A line written every time would make the one that matters
    // unreadable in a pull request.
    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(0);
    expect(result.stdout).toStrictEqual([]);
  });
});

test("updating a contract leaves every SKILL.md byte identical", async () => {
  await withGoodTree(async (root) => {
    // A declaration names ids and never digests, so nothing about a contract's
    // text reaches a SKILL.md. Were a digest pinned there instead, every
    // contract update would touch every skill declaring it — a diff on files
    // whose dependency intent did not change, and tokens spent reading it every
    // time the skill is loaded.
    const before = new Map<string, string>();
    for (const name of ["release-notes", "review-writer"]) {
      before.set(
        name,
        await fs.readFile(`${root}/skills/${name}/SKILL.md`, "utf8"),
      );
    }
    await append(`${root}/contracts/verdict-format.md`, "\nOne more rule.\n");

    expect((await runCli(["gen", "--root", root])).code).toStrictEqual(0);
    for (const [name, text] of before) {
      expect(
        await fs.readFile(`${root}/skills/${name}/SKILL.md`, "utf8"),
        name,
      ).toStrictEqual(text);
    }
  });
});

test("rewriting the lock for one contract leaves another's resolution alone", async () => {
  await withGoodTree(async (root) => {
    const before = (await readLockFile(root)).resolutions["changelog-entry"];
    await append(`${root}/contracts/verdict-format.md`, "\nOne more rule.\n");

    expect((await runCli(["gen", "--root", root])).code).toStrictEqual(0);
    expect(
      (await readLockFile(root)).resolutions["changelog-entry"],
    ).toStrictEqual(before);
  });
});

test("gen records a conformance digest for a declared contract that gains tests", async () => {
  await withGoodTree(async (root) => {
    // verdict-format ships no conformance tests, so nothing is recorded for it.
    // Adding tests has to add the digest, and verification digests them from
    // then on.
    expect(
      "conformance" in (await readLockFile(root)).resolutions["verdict-format"],
    ).toStrictEqual(false);
    await writeFile(
      `${root}/contracts/verdict-format/conformance/cases/first.md`,
      "a new case\n",
    );

    expect((await runCli(["gen", "--root", root])).code).toStrictEqual(0);
    expect(
      (await readLockFile(root)).resolutions["verdict-format"].conformance,
    ).toMatch(/^sha256:[0-9a-f]{64}$/);
    expect((await runCli(["verify", "--root", root])).code).toStrictEqual(0);
  });
});

test("gen drops the conformance digest of a declared contract that loses its tests", async () => {
  await withGoodTree(async (root) => {
    // The other direction, and the one a carried-across resolution gets wrong:
    // a digest kept for tests that are gone fails every later verification.
    await fs.rm(`${root}/contracts/changelog-entry`, { recursive: true });

    expect((await runCli(["gen", "--root", root])).code).toStrictEqual(0);
    expect(
      "conformance" in
        (await readLockFile(root)).resolutions["changelog-entry"],
    ).toStrictEqual(false);
    expect((await runCli(["verify", "--root", root])).code).toStrictEqual(0);
  });
});

test("gen reports a conformance digest it recorded in place of another", async () => {
  await withGoodTree(async (root) => {
    // The contract's own text is untouched, so the text line says nothing. The
    // conformance tree is the compatibility evidence a consuming repository
    // matches its own results against, and a run that swapped which evidence
    // the lock names has to say so — silence here reads as a run that changed
    // nothing at all.
    const before = (await readLockFile(root)).resolutions["changelog-entry"]
      .conformance;
    await append(
      `${root}/contracts/changelog-entry/conformance/cases/minimal.md`,
      "\nOne further case.\n",
    );

    const result = await runCli(["gen", "--root", root]);
    expect(
      result.code,
      result.stdout.concat(result.stderr).join("\n"),
    ).toStrictEqual(0);
    const after = (await readLockFile(root)).resolutions["changelog-entry"]
      .conformance;
    expect(result.stdout).toStrictEqual([
      `adopted: changelog-entry conformance ${before} -> ${after}`,
    ]);
  });
});

test("gen reports a conformance digest it recorded for the first time", async () => {
  await withGoodTree(async (root) => {
    // verdict-format ships no conformance tests, so the lock records none for
    // it. Gaining them binds evidence the lock never named before, which is the
    // same event as a first adoption of text and is reported the same way.
    await writeFile(
      `${root}/contracts/verdict-format/conformance/cases/first.md`,
      "a new case\n",
    );

    const result = await runCli(["gen", "--root", root]);
    expect(
      result.code,
      result.stdout.concat(result.stderr).join("\n"),
    ).toStrictEqual(0);
    const digest = (await readLockFile(root)).resolutions["verdict-format"]
      .conformance;
    expect(result.stdout).toStrictEqual([
      `adopted: verdict-format conformance ${digest} (initial adoption)`,
    ]);
  });
});

test("gen reports the conformance digest it dropped when a contract loses its tests", async () => {
  await withGoodTree(async (root) => {
    // Reported as a retirement rather than an adoption: what happened is that a
    // value left the lock, which is what `retired` already means for a whole
    // resolution. Nothing was taken up in its place.
    const before = (await readLockFile(root)).resolutions["changelog-entry"]
      .conformance;
    await fs.rm(`${root}/contracts/changelog-entry`, { recursive: true });

    const result = await runCli(["gen", "--root", root]);
    expect(
      result.code,
      result.stdout.concat(result.stderr).join("\n"),
    ).toStrictEqual(0);
    expect(result.stdout).toStrictEqual([
      `retired: changelog-entry conformance ${before} ` +
        `(no conformance tests; digest removed from the lock)`,
    ]);
  });
});

test("gen reports a text change and a conformance change of one contract on separate lines", async () => {
  await withGoodTree(async (root) => {
    // Two facts, two lines. Folded into one, a reader would have to parse the
    // line to find out which of the two digests moved, and the text form the
    // consuming regression machinery already matches against would change shape
    // whenever the conformance tree happened to move in the same run.
    const before = (await readLockFile(root)).resolutions["changelog-entry"];
    await append(
      `${root}/contracts/changelog-entry.md`,
      "\n- One more rule.\n",
    );
    await append(
      `${root}/contracts/changelog-entry/conformance/cases/minimal.md`,
      "\nOne further case.\n",
    );

    const result = await runCli(["gen", "--root", root]);
    expect(
      result.code,
      result.stdout.concat(result.stderr).join("\n"),
    ).toStrictEqual(0);
    const after = (await readLockFile(root)).resolutions["changelog-entry"];
    expect(result.stdout).toStrictEqual([
      `adopted: changelog-entry ${before.digest} -> ${after.digest}`,
      `adopted: changelog-entry conformance ${before.conformance} -> ${after.conformance}`,
    ]);
  });
});

test("a retired resolution is reported once, not again for the conformance digest it held", async () => {
  await withGoodTree(async (root) => {
    // The whole resolution left the lock, and its conformance digest left with
    // it. A second line about the digest would report the same removal twice.
    for (const name of ["release-notes", "review-writer"]) {
      await fs.writeFile(
        `${root}/skills/${name}/SKILL.md`,
        `---\nname: ${name}\n---\n\n# ${name}\n`,
      );
    }
    await fs.rm(`${root}/contracts/changelog-entry.md`);
    await fs.rm(`${root}/contracts/changelog-entry`, { recursive: true });

    const result = await runCli(["gen", "--root", root]);
    expect(
      result.code,
      result.stdout.concat(result.stderr).join("\n"),
    ).toStrictEqual(0);
    expect(
      result.stdout.filter((line) => line.includes("changelog-entry")),
    ).toStrictEqual([
      "retired: changelog-entry (no canonical text; resolution removed from the lock)",
    ]);
  });
});

/**
 * Leaves changelog-entry recorded in the lock with its text present, but
 * declared by nobody: release-notes takes up the other contract instead of it,
 * and review-writer simply drops it, so no declaration list is left empty.
 */
async function withdrawDeclarationsOf(root: string): Promise<void> {
  const skill = `${root}/skills/release-notes/SKILL.md`;
  await fs.writeFile(
    skill,
    (await fs.readFile(skill, "utf8")).replace(
      "    - changelog-entry\n",
      "    - verdict-format\n",
    ),
  );
  const reviewer = `${root}/skills/review-writer/SKILL.md`;
  await fs.writeFile(
    reviewer,
    (await fs.readFile(reviewer, "utf8")).replace(
      "    - changelog-entry\n",
      "",
    ),
  );
}

test("editing the canonical text of a contract no skill declares is reported as a stale lock", async () => {
  await withGoodTree(async (root) => {
    // The text twin of the conformance case below. verify compared the lock
    // against the contracts a declaration names, while gen rewrites the lock
    // over every contract the lock records as well — so this edit left verify
    // reporting a clean tree, and the next gen recorded the new digest with
    // nothing having reported the change. Whichever set gen would act on is the
    // set verify has to judge.
    await withdrawDeclarationsOf(root);
    const settled = await runCli(["gen", "--root", root]);
    expect(
      settled.code,
      settled.stdout.concat(settled.stderr).join("\n"),
    ).toStrictEqual(0);
    expect((await runCli(["verify", "--root", root])).code).toStrictEqual(0);
    const recorded = (await readLockFile(root)).resolutions["changelog-entry"]
      .digest;

    await append(
      `${root}/contracts/changelog-entry.md`,
      "\n- One more rule.\n",
    );

    const result = await runCli(["verify", "--root", root]);
    expect(
      result.code,
      result.stdout.concat(result.stderr).join("\n"),
    ).toStrictEqual(1);
    expect(kindsOf(result.stdout)).toContain("stale-lock");
    expect(
      result.stdout.find((line) => line.startsWith("stale-lock:")),
    ).toContain(recorded);
  });
});

test("a contract no skill declares is not reported as unresolved when the lock has no entry for it", async () => {
  await withGoodTree(async (root) => {
    // Only a declaration can be unresolved: it is the declaration that asks for
    // a pin. A contract whose text merely sits in contracts/, declared by
    // nobody and recorded by nothing, is not a state to report — reporting it
    // would make every stray document under contracts/ a violation.
    await withdrawDeclarationsOf(root);
    expect((await runCli(["gen", "--root", root])).code).toStrictEqual(0);
    const lock = await readLockFile(root);
    delete lock.resolutions["changelog-entry"];
    await writeLockFile(root, lock);

    const result = await runCli(["verify", "--root", root]);
    expect(kindsOf(result.stdout)).not.toContain("unresolved");
  });
});

test("gen rewrites the conformance digest of a contract no skill declares", async () => {
  await withGoodTree(async (root) => {
    // The lock still records the contract and the tree still holds its text,
    // but nothing declares it. Verification digests the conformance tests of
    // every resolution the lock records, so a tree left in this state fails
    // forever unless gen rewrites resolutions it reaches through the lock
    // rather than only those a declaration names.
    // Both skills stop declaring it and take up the other contract instead, so
    // no declaration list is left empty and changelog-entry is reached only
    // through the lock.
    const skill = `${root}/skills/release-notes/SKILL.md`;
    await fs.writeFile(
      skill,
      (await fs.readFile(skill, "utf8")).replace(
        "    - changelog-entry\n",
        "    - verdict-format\n",
      ),
    );
    const reviewer = `${root}/skills/review-writer/SKILL.md`;
    await fs.writeFile(
      reviewer,
      (await fs.readFile(reviewer, "utf8")).replace(
        "    - changelog-entry\n",
        "",
      ),
    );
    const regenerated = await runCli(["gen", "--root", root]);
    expect(
      regenerated.code,
      regenerated.stdout.concat(regenerated.stderr).join("\n"),
    ).toStrictEqual(0);
    await append(
      `${root}/contracts/changelog-entry/conformance/cases/minimal.md`,
      "\nOne further case.\n",
    );
    expect((await runCli(["verify", "--root", root])).code).toStrictEqual(1);

    const result = await runCli(["gen", "--root", root]);
    expect(
      result.code,
      result.stdout.concat(result.stderr).join("\n"),
    ).toStrictEqual(0);
    expect((await runCli(["verify", "--root", root])).code).toStrictEqual(0);
  });
});

test("gen refuses a declared contract with no canonical file and writes nothing", async () => {
  await withGoodTree(async (root) => {
    await fs.rm(`${root}/contracts/verdict-format.md`);
    const before = await snapshotTree(root);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(1);
    expect(kindsOf(result.stdout)).toStrictEqual(["closure"]);
    expect(await snapshotTree(root)).toStrictEqual(before);
  });
});

test("gen removes a vendored copy no declaration accounts for", async () => {
  await withGoodTree(async (root) => {
    const orphan = "skills/release-notes/references/vendor/orphan.md";
    await writeFile(`${root}/${orphan}`, "left over from an old declaration\n");

    expect((await runCli(["gen", "--root", root])).code).toStrictEqual(0);
    expect((await snapshotTree(root)).has(orphan)).toStrictEqual(false);
  });
});

test("adding a dependency on an already recorded contract needs no other change", async () => {
  await withGoodTree(async (root) => {
    const skill = `${root}/skills/release-notes/SKILL.md`;
    await fs.writeFile(
      skill,
      (await fs.readFile(skill, "utf8")).replace(
        "    - changelog-entry\n",
        "    - changelog-entry\n    - verdict-format\n",
      ),
    );

    const result = await runCli(["gen", "--root", root]);
    expect(
      result.code,
      result.stdout.concat(result.stderr).join("\n"),
    ).toStrictEqual(0);
    expect(
      (await readLockFile(root)).dependencies["release-notes"],
    ).toStrictEqual(["changelog-entry", "verdict-format"]);
    expect(
      await fs.readFile(
        `${root}/skills/release-notes/references/vendor/verdict-format.md`,
        "utf8",
      ),
    ).toContain("# Verdict Format");
  });
});

test("gen refuses a skill whose declaration cannot be read and keeps its vendored copies", async () => {
  await withGoodTree(async (root) => {
    const skill = `${root}/skills/review-writer/SKILL.md`;
    await fs.writeFile(
      skill,
      (await fs.readFile(skill, "utf8")).replace(
        "metadata:\n",
        "metadata:\n  audience: internal\nmetadata:\n",
      ),
    );
    const before = await snapshotTree(root);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    expect(result.stderr.join("\n")).toContain("error:");
    expect(await snapshotTree(root)).toStrictEqual(before);
  });
});

test("a dependent skill name with control bytes is quoted in the closure finding", async () => {
  await withGoodTree(async (root) => {
    // The closure finding names the skills that declare the contract; a skill
    // name holding an ANSI escape would paint the terminal on the line.
    const name = "esc\u001b[31m";
    await writeFile(
      `${root}/skills/${name}/SKILL.md`,
      "---\nname: esc\nmetadata:\n  contracts:\n    - verdict-format\n---\n\n# esc\n",
    );
    await fs.rm(`${root}/contracts/verdict-format.md`);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(1);
    const closure = result.stdout.find((line) => line.startsWith("closure:"));
    expect(closure).toBeDefined();
    expect(closure).not.toContain("\u001b");
    expect(closure).toContain("\\u001b");
  });
});

test("gen refuses a vendor directory symlinked outside the tree", async () => {
  await withGoodTree(async (root) => {
    const outside = `${root.slice(0, root.lastIndexOf("/"))}/outside`;
    await fs.mkdir(outside, { recursive: true });
    await replaceWithSymlink(
      `${root}/skills/release-notes/references/vendor`,
      outside,
    );
    const outsideBefore = await snapshotTree(outside);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    expect(result.stderr.join("\n")).toContain("error:");
    expect(await snapshotTree(outside)).toStrictEqual(outsideBefore);
  });
});

test("gen refuses a symlink planted at the lock temporary path", async () => {
  await withGoodTree(async (root) => {
    const outside = `${root.slice(0, root.lastIndexOf("/"))}/outside`;
    await writeFile(`${outside}/target.json`, "must not be overwritten\n");
    await fs.rm(`${root}/${COPY}`);
    await replaceWithSymlink(`${root}/${LOCK}.tmp`, `${outside}/target.json`);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    expect(await fs.readFile(`${outside}/target.json`, "utf8")).toStrictEqual(
      "must not be overwritten\n",
    );
  });
});

test("gen exits 2 naming the path when a vendored copy cannot be written", async () => {
  await withGoodTree(async (root) => {
    await fs.rm(`${root}/${COPY}`);
    await fs.mkdir(`${root}/${COPY}`);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    expect(result.stderr.join("\n")).toContain("verdict-format.md");
  });
});

test("a run interrupted by an unwritable copy leaves every other file in place", async () => {
  await withGoodTree(async (root) => {
    const blocked = "skills/review-writer/references/vendor/changelog-entry.md";
    await fs.rm(`${root}/${blocked}`);
    await fs.mkdir(`${root}/${blocked}`);

    expect((await runCli(["gen", "--root", root])).code).toStrictEqual(2);
    const after = await snapshotTree(root);
    expect(after.has(COPY)).toStrictEqual(true);
    expect(after.has(LOCK)).toStrictEqual(true);
    expect(
      after.has("skills/release-notes/references/vendor/changelog-entry.md"),
    ).toStrictEqual(true);
  });
});

// The five shapes a planted link can take on the way to the text this tool
// reads. They are stated together because each is reached through a different
// primitive, so a guard proven on one says nothing about the other four — and
// two of them were open while the other three were closed.
//
// A directory link is the dangerous half: every path below it resolves outside
// the boundary the run was pointed at, so the run reads outside text, pins its
// digest, and writes it into the tree while reporting nothing.

test("gen refuses a contracts directory symlinked outside the tree", async () => {
  await withGoodTree(async (root) => {
    const outside = await escapeThrough(root, "contracts");
    // The moved text is edited before the run, so that a run which followed the
    // link would leave a trace: the copies it wrote would carry the outside
    // text, which the tree snapshot below catches. Left byte identical,
    // following the link and refusing it would leave the same tree behind.
    const escaped = `${outside}/contracts/verdict-format.md`;
    await fs.writeFile(
      escaped,
      (await fs.readFile(escaped, "utf8")) + "\nOne more rule.\n",
    );
    const outsideBefore = await snapshotTree(outside);
    const treeBefore = await snapshotTree(root);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    // Named as the directory itself: readContracts asks what stands at
    // contracts/ once, before any contract below it is looked up, so the
    // refusal quotes the link the run was pointed at rather than whichever
    // file happened to be reached through it.
    expect(result.stderr.join("\n")).toContain(
      "symlink is not allowed inside the tree: contracts",
    );
    expect(result.stderr.join("\n")).not.toMatch(
      /symlink is not allowed inside the tree: contracts\/[^\s]+\.md/,
    );
    expect(await snapshotTree(outside)).toStrictEqual(outsideBefore);
    expect(await snapshotTree(root)).toStrictEqual(treeBefore);
  });
});

test("verify refuses a contracts directory symlinked outside the tree", async () => {
  await withGoodTree(async (root) => {
    await escapeThrough(root, "contracts");
    const result = await runCli(["verify", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
  });
});

test("gen and verify both refuse a contract's own directory symlinked outside the tree", async () => {
  await withGoodTree(async (root) => {
    // A link at the directory a contract's conformance tests live in. Only
    // verify ever reads through that directory, so the two commands used to
    // answer the same planted link differently: verify stopped, gen expanded
    // the tree and said nothing. Whether a link is refused is a fact about the
    // tree, so it cannot depend on which command is looking.
    const outside = await escapeThrough(root, "contracts/changelog-entry");
    const outsideBefore = await snapshotTree(outside);
    const treeBefore = await snapshotTree(root);

    for (const command of ["gen", "verify"]) {
      const result = await runCli([command, "--root", root]);
      expect(result.code, command).toStrictEqual(2);
      expect(result.stdout, command).toStrictEqual([]);
      expect(result.stderr.join("\n"), command).toContain(
        "symlink is not allowed inside the tree: contracts/changelog-entry",
      );
    }
    expect(await snapshotTree(outside)).toStrictEqual(outsideBefore);
    expect(await snapshotTree(root)).toStrictEqual(treeBefore);
  });
});

test("a contract's own directory symlinked outside the tree is refused before the lock is rewritten", async () => {
  await withGoodTree(async (root) => {
    // The link stands at a contract whose resolution was dropped, which on its
    // own is a state the run simply rewrites the lock over. Following the link
    // would therefore record outside text as what the tree holds. The run could
    // not find out what the tree says, so it stops on the way to the canonical
    // text, before anything is derived from it.
    const lock = await readLockFile(root);
    delete lock.resolutions["changelog-entry"];
    await writeLockFile(root, lock);
    const outside = await escapeThrough(root, "contracts/changelog-entry");
    const outsideBefore = await snapshotTree(outside);
    const treeBefore = await snapshotTree(root);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    expect(result.stderr.join("\n")).toContain(
      "symlink is not allowed inside the tree: contracts/changelog-entry",
    );
    expect(await snapshotTree(outside)).toStrictEqual(outsideBefore);
    expect(await snapshotTree(root)).toStrictEqual(treeBefore);
  });
});

test("every command reading contracts refuses a contract file symlinked outside the tree", async () => {
  await withGoodTree(async (root) => {
    // The canonical text itself, rather than a directory on the way to it: a
    // link here resolves outside the tree, and a run that read through it
    // would digest outside text and write it into every vendored copy.
    const outside = await escapeThrough(root, "contracts/verdict-format.md");
    const outsideBefore = await snapshotTree(outside);
    const treeBefore = await snapshotTree(root);

    for (const command of ["gen", "verify"]) {
      const result = await runCli([command, "--root", root]);
      expect(result.code, command).toStrictEqual(2);
      expect(result.stdout, command).toStrictEqual([]);
      expect(result.stderr.join("\n"), command).toContain(
        "symlink is not allowed inside the tree: contracts/verdict-format.md",
      );
    }
    expect(await snapshotTree(outside)).toStrictEqual(outsideBefore);
    expect(await snapshotTree(root)).toStrictEqual(treeBefore);
  });
});

test("every command reading contracts refuses a conformance directory symlinked outside the tree", async () => {
  await withGoodTree(async (root) => {
    // The deepest of the directory shapes, and the one that used to answer two
    // ways: verify digests the tests below it and stopped, while gen — which
    // never reads them — expanded the tree.
    const outside = await escapeThrough(
      root,
      "contracts/changelog-entry/conformance",
    );
    const outsideBefore = await snapshotTree(outside);
    const treeBefore = await snapshotTree(root);

    for (const command of [["gen"], ["verify"]]) {
      const result = await runCli([...command, "--root", root]);
      expect(result.code, command[0]).toStrictEqual(2);
      expect(result.stdout, command[0]).toStrictEqual([]);
      expect(result.stderr.join("\n"), command[0]).toContain(
        "symlink is not allowed inside the tree: contracts/changelog-entry/conformance",
      );
    }
    expect(await snapshotTree(outside)).toStrictEqual(outsideBefore);
    expect(await snapshotTree(root)).toStrictEqual(treeBefore);
  });
});

test("verify refuses a skills directory symlinked outside the tree", async () => {
  await withGoodTree(async (root) => {
    const outside = await escapeThrough(root, "skills");
    const outsideBefore = await snapshotTree(outside);

    const result = await runCli(["verify", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    expect(await snapshotTree(outside)).toStrictEqual(outsideBefore);
  });
});

test("gen refuses a skill directory that is itself a symlink", async () => {
  await withGoodTree(async (root) => {
    // Read as an ordinary entry the link is not a directory, so the skill drops
    // out of the list without a word: its declarations stop being seen and its
    // dependency edge leaves the lock. Refusing is what keeps that silent.
    await escapeThrough(root, "skills/release-notes");

    const result = await runCli(["verify", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    expect(result.stderr.join("\n")).toContain(
      "symlink is not allowed inside the tree: skills/release-notes",
    );
  });
});

test("gen refuses a symlink standing among a skill's vendored copies", async () => {
  await withGoodTree(async (root) => {
    // Treated as an ordinary name it answers to no declaration, so the run
    // would quietly delete it as an unaccounted copy.
    const link = "skills/release-notes/references/vendor/orphan.md";
    await replaceWithSymlink(`${root}/${link}`, `${root}/${COPY}`);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    expect(result.stderr.join("\n")).toContain(
      `symlink is not allowed inside the tree: ${link}`,
    );
  });
});

test("gen refuses a vendor directory reached through a symlinked parent", async () => {
  await withGoodTree(async (root) => {
    // The link is one level above the vendor directory, so checking only the
    // directory itself finds a plain directory and reports nothing — while
    // every copy written and every stray removed lands outside the tree.
    const outside = `${root.slice(0, root.lastIndexOf("/"))}/outside`;
    await writeFile(`${outside}/references/vendor/stray.md`, "not ours\n");
    await replaceWithSymlink(
      `${root}/skills/release-notes/references`,
      `${outside}/references`,
    );
    const outsideBefore = await snapshotTree(outside);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    expect(result.stderr.join("\n")).toContain(
      "symlink is not allowed inside the tree: skills/release-notes/references/vendor",
    );
    expect(await snapshotTree(outside)).toStrictEqual(outsideBefore);
  });
});

test("gen refuses a lock symlinked outside the tree before reading it", async () => {
  await withGoodTree(async (root) => {
    // Refused where it is read, not merely where it is written. Left to the
    // write, the run would first adopt an outside lock and expand the whole
    // tree from it, and only then stop.
    const outside = `${root.slice(0, root.lastIndexOf("/"))}/outside`;
    await fs.mkdir(outside, { recursive: true });
    await fs.rename(`${root}/${LOCK}`, `${outside}/${LOCK}`);
    await fs.symlink(`${outside}/${LOCK}`, `${root}/${LOCK}`);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    expect(result.stderr.join("\n")).toContain(
      `symlink is not allowed inside the tree: ${LOCK}`,
    );
  });
});

test("a run stopped by an unwritable copy has removed nothing and rewritten no lock", async () => {
  await withGoodTree(async (root) => {
    // Copies, then the lock, then the removals. The order is what decides
    // what an interrupted run leaves: a removal done first would lose a file
    // the run never replaced, and a lock written first would describe a
    // tree that was never built.
    const orphan = "skills/release-notes/references/vendor/orphan.md";
    await writeFile(`${root}/${orphan}`, "left over from an old declaration\n");
    const skill = `${root}/skills/release-notes/SKILL.md`;
    await fs.writeFile(
      skill,
      (await fs.readFile(skill, "utf8")).replace(
        "    - changelog-entry\n",
        "    - changelog-entry\n    - verdict-format\n",
      ),
    );
    const blocked = "skills/review-writer/references/vendor/changelog-entry.md";
    await fs.rm(`${root}/${blocked}`);
    await fs.mkdir(`${root}/${blocked}`);
    const lockBefore = await fs.readFile(`${root}/${LOCK}`, "utf8");

    expect((await runCli(["gen", "--root", root])).code).toStrictEqual(2);
    expect((await snapshotTree(root)).has(orphan)).toStrictEqual(true);
    expect(await fs.readFile(`${root}/${LOCK}`, "utf8")).toStrictEqual(
      lockBefore,
    );
  });
});

test("gen refuses a skill whose opening delimiter is not exactly the delimiter and keeps its vendored copies", async () => {
  await withGoodTree(async (root) => {
    const skill = `${root}/skills/release-notes/SKILL.md`;
    const lines = (await fs.readFile(skill, "utf8")).split("\n");
    lines[0] = "--- ";
    await fs.writeFile(skill, lines.join("\n"));
    const before = await snapshotTree(root);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    expect(await snapshotTree(root)).toStrictEqual(before);
  });
});

test("gen refuses a skill whose opening delimiter carries a zero-width character and keeps its vendored copies", async () => {
  await withGoodTree(async (root) => {
    const skill = `${root}/skills/release-notes/SKILL.md`;
    const lines = (await fs.readFile(skill, "utf8")).split("\n");
    lines[0] = "\u200b---";
    await fs.writeFile(skill, lines.join("\n"));
    const before = await snapshotTree(root);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    expect(await snapshotTree(root)).toStrictEqual(before);
  });
});

test("gen refuses a skill reaching its opening delimiter only after a blank line and keeps its vendored copies", async () => {
  await withGoodTree(async (root) => {
    const skill = `${root}/skills/release-notes/SKILL.md`;
    await fs.writeFile(skill, "\n" + (await fs.readFile(skill, "utf8")));
    const before = await snapshotTree(root);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(2);
    expect(result.stdout).toStrictEqual([]);
    expect(await snapshotTree(root)).toStrictEqual(before);
  });
});

const describeRemoval = PERMISSIONS_APPLY ? test : test.skip;

describeRemoval(
  "gen refuses a stale vendored copy it could not remove, having written everything else",
  async () => {
    await withGoodTree(async (root) => {
      // The removals run last, so a failure here finds every copy and the lock
      // already in place: what is left over is the one thing the run could not
      // clear. Passed over in silence, gen answered 0 while verify reported the
      // leftover as an extra — and running gen again changed neither answer, so
      // the two commands disagreed for as long as the tree stayed that way.
      const orphan = "skills/release-notes/references/vendor/orphan.md";
      await writeFile(`${root}/${orphan}/inside.md`, "blocks the removal\n");
      await fs.rm(`${root}/${COPY}`);

      await withUnreadable(`${root}/${orphan}`, async () => {
        const result = await runCli(["gen", "--root", root]);
        expect(result.code).toStrictEqual(2);
        expect(result.stdout).toStrictEqual([]);
        expect(result.stderr.join("\n")).toContain(orphan);
      });

      // What the run did finish is still there: the copy deleted above was
      // written back before the removals were attempted.
      expect(await fs.readFile(`${root}/${COPY}`, "utf8")).toContain(
        "# Verdict Format",
      );
    });
  },
);

test("every command refuses a declared contract whose canonical text is not a regular file", async () => {
  await withGoodTree(async (root) => {
    // The same shape one step earlier, where a declaration still names the
    // contract. Text that is not there at all is a closure gap — a fact about
    // the tree, reported with exit 1. A directory standing where the text
    // belongs is not that fact: the run cannot find out what the contract says,
    // which is what separates a report from a refusal.
    await fs.rm(`${root}/contracts/verdict-format.md`);
    await fs.mkdir(`${root}/contracts/verdict-format.md`);
    const before = await snapshotTree(root);

    for (const command of [["gen"], ["verify"]]) {
      const result = await runCli([...command, "--root", root]);
      expect(result.code, command[0]).toStrictEqual(2);
      expect(result.stdout, command[0]).toStrictEqual([]);
      expect(result.stderr.join("\n"), command[0]).toContain(
        "contracts/verdict-format.md: not a regular file",
      );
    }
    expect(await snapshotTree(root)).toStrictEqual(before);
  });
});

// Every path the run writes through, blocked by something it must not open.
// A named pipe passes the check for links — it is not one — and the open then
// waits for a reader that never comes. The tests carry their own deadline so a
// regression fails in seconds instead of stopping the suite for good.

const WRITE_TARGETS = [
  "skills/review-writer/references/vendor/verdict-format.md",
  "skills/review-writer/references/vendor/verdict-format.md.tmp",
  `${LOCK}.tmp`,
];

test("gen refuses a named pipe standing where the run would write", async () => {
  for (const site of WRITE_TARGETS) {
    await withGoodTree(async (root) => {
      await fs.rm(`${root}/${site}`).catch(() => {});
      await promisify(execFile)("mkfifo", [`${root}/${site}`]);

      const result = await runCli(["gen", "--root", root]);
      expect(result.code, site).toStrictEqual(2);
      expect(result.stderr.join("\n"), site).toContain(site);
      // Left as it was found: refusing is not a licence to clear the path.
      expect((await fs.lstat(`${root}/${site}`)).isFIFO(), site).toStrictEqual(
        true,
      );
    });
  }
}, 15000);

/** Declares a contract named after an inherited property, and puts its text there. */
async function declareInheritedProperty(root: string): Promise<void> {
  await fs.copyFile(
    `${root}/contracts/verdict-format.md`,
    `${root}/contracts/constructor.md`,
  );
  const skill = `${root}/skills/release-notes/SKILL.md`;
  await fs.writeFile(
    skill,
    (await fs.readFile(skill, "utf8")).replace(
      "    - changelog-entry\n",
      "    - changelog-entry\n    - constructor\n",
    ),
  );
}

test("a contract named for an inherited property is reported as unresolved, not as drift against nothing", async () => {
  await withGoodTree(async (root) => {
    // `constructor` is a usable contract id, and looking it up in a plain
    // object finds Object's own constructor rather than nothing. Verification
    // then judges the text against a resolution that was never recorded, and
    // says it drifted from a digest of `undefined` instead of saying the lock
    // records nothing for it.
    await declareInheritedProperty(root);

    const result = await runCli(["verify", "--root", root]);
    expect(result.code).toStrictEqual(1);
    expect(kindsOf(result.stdout)).toContain("unresolved");
    expect(result.stdout[0]).toContain("constructor");
    expect(result.stdout[0].startsWith("unresolved:")).toBe(true);
  });
});

test("a contract named for an inherited property is recorded under its own key", async () => {
  await withGoodTree(async (root) => {
    // The writing side of the same read. Assigned into a plain object the
    // resolution would set the prototype instead of an entry, so the lock
    // would come back without the contract and the next run would report it
    // unresolved for ever.
    await declareInheritedProperty(root);

    const result = await runCli(["gen", "--root", root]);
    expect(
      result.code,
      result.stdout.concat(result.stderr).join("\n"),
    ).toStrictEqual(0);
    expect(
      Object.getOwnPropertyDescriptor(
        (await readLockFile(root)).resolutions,
        "constructor",
      )?.value.digest,
    ).toMatch(/^sha256:[0-9a-f]{64}$/);
    expect((await runCli(["verify", "--root", root])).code).toStrictEqual(0);
  });
});

// The same inherited-property read, on the two paths that answer "nothing is
// resolved yet" rather than reading recorded resolutions: a tree with no
// lock at all, and a lock whose recorded resolutions are empty. Both are
// what a repository adopting this tool starts from.

const EMPTY_LOCK_SHAPES: {
  what: string;
  write: (root: string) => Promise<void>;
}[] = [
  {
    what: "no lock at all",
    write: async (root) => await fs.rm(`${root}/${LOCK}`),
  },
  {
    what: "a lock recording no resolutions",
    write: async (root) =>
      await fs.writeFile(
        `${root}/${LOCK}`,
        '{"dependencies":{"release-notes":["changelog-entry","constructor"]},"resolutions":{}}\n',
      ),
  },
];

test("a contract named for an inherited property is unresolved on a tree that has resolved nothing", async () => {
  for (const { what, write } of EMPTY_LOCK_SHAPES) {
    await withGoodTree(async (root) => {
      await declareInheritedProperty(root);
      await write(root);

      const result = await runCli(["verify", "--root", root]);
      const line = result.stdout.find((entry) => entry.includes("constructor"));
      expect(line, what).toBeDefined();
      expect(line?.startsWith("unresolved:"), `${what}: ${line}`).toBe(true);
    });
  }
});

test("a contract named for an inherited property is recorded on a tree that has resolved nothing", async () => {
  for (const { what, write } of EMPTY_LOCK_SHAPES) {
    await withGoodTree(async (root) => {
      await declareInheritedProperty(root);
      await write(root);

      const result = await runCli(["gen", "--root", root]);
      expect(
        result.code,
        `${what}: ${result.stdout.concat(result.stderr).join("\n")}`,
      ).toStrictEqual(0);
      expect(
        Object.getOwnPropertyDescriptor(
          (await readLockFile(root)).resolutions,
          "constructor",
        )?.value.digest,
        what,
      ).toMatch(/^sha256:[0-9a-f]{64}$/);
      expect(
        (await runCli(["verify", "--root", root])).code,
        what,
      ).toStrictEqual(0);
    });
  }
});

test("a removed canonical text with its declaration left behind keeps its resolution", async () => {
  await withGoodTree(async (root) => {
    // The skill still declares the contract, so gen stops on the closure gap
    // and never reaches the plan that would prune the resolution: only a
    // withdrawal — declaration removed too — retires it.
    await fs.rm(`${root}/contracts/verdict-format.md`);

    const result = await runCli(["gen", "--root", root]);
    expect(result.code).toStrictEqual(1);
    expect(result.stdout.join("\n")).toContain("closure");
    expect(
      "verdict-format" in (await readLockFile(root)).resolutions,
    ).toStrictEqual(true);
  });
});
