// header.ts — the fixed prefix every generated copy carries, as bytes verify
// compares exactly.

/**
 * The name the vendored copy header credits the generation to.
 *
 * Frozen at `agentic-skill-vendor` from here on. It is a value on the wire, not
 * a path: it sits in bytes that verify compares exactly, so changing it reports
 * every already generated copy in every consuming repository as drift. It was
 * `vendor.ts` — the name of the single file the tool used to be — and moving it
 * to the published name is the last time it may move, taken while no version
 * has been released and no copy exists to break.
 *
 * The name is all that is left of what used to be a generator record. The
 * version and the repository URL that stood beside it were written into the
 * manifest, where no check consumed them and the version made a release of the
 * tool fail every consuming repository's verify.
 */
export const GENERATOR_NAME = "agentic-skill-vendor";

/**
 * The fixed prefix of a vendored copy, rebuilt from an id and a pinned digest.
 * A raw-byte directory dest carries the same bytes as a file of its own.
 */
export function vendorHeader(id: string, digest: string): string {
  return (
    `<!-- DO NOT EDIT. Generated by ${GENERATOR_NAME}. -->\n` +
    `<!-- contract: ${id} -->\n` +
    `<!-- source-digest: ${digest} -->\n\n`
  );
}
