import { expect, test } from "bun:test";
import * as fs from "node:fs/promises";
import { fileURLToPath } from "node:url";
import type { Sink } from "./errors.ts";
import {
  runCli,
  snapshotTree,
  withEmptyDir,
  withGoodTree,
} from "./test-support/testing.ts";

const SOURCE_DIR = fileURLToPath(new URL(".", import.meta.url));
const MODULES = fileURLToPath(new URL("../node_modules", import.meta.url));
const PACKAGE_MANIFEST = fileURLToPath(
  new URL("../package.json", import.meta.url),
);
const ENTRY = "cli.ts";

/**
 * Loads a copy of the tool with one edit applied to one of its modules,
 * standing in for the tool having been altered between the version a consumer
 * reviewed and the run. The whole source directory is copied, because a module
 * that no longer sits beside the ones it imports would fail to load for a
 * reason that has nothing to do with what the edit changed.
 */
async function runAltered(
  dir: string,
  file: string,
  find: string,
  replaceWith: string,
): Promise<{ code: number; stdout: string[] }> {
  const tool = `${dir}/tool`;
  await fs.cp(SOURCE_DIR, tool, { recursive: true });
  // A package specifier is resolved by walking the directories above the
  // module, so a copy of the tool placed under the OS temporary directory
  // would find no node_modules at all. Linking the real one beside the copy
  // is what lets the copy import what the original imports.
  await fs.symlink(MODULES, `${dir}/node_modules`);
  // The tool reads its own version out of the package manifest one directory
  // above it, so the copy needs one there too. Without it the copy fails to
  // load at all, and every case here would report that instead of what its
  // edit changed.
  await fs.copyFile(PACKAGE_MANIFEST, `${dir}/package.json`);
  const path = `${tool}/${file}`;
  const source = await fs.readFile(path, "utf8");
  expect(source).toContain(find);
  await fs.writeFile(path, source.replace(find, replaceWith));

  const module = (await import(`file://${tool}/${ENTRY}`)) as {
    run: (argv: string[], out: Sink, err: Sink) => Promise<number>;
  };
  const stdout: string[] = [];
  const code = await module.run(
    ["self-test"],
    (l) => stdout.push(l),
    () => {},
  );
  return { code, stdout };
}

test("self-test passes against the vectors the tool carries", async () => {
  const result = await runCli(["self-test"]);
  expect(result.stdout).toStrictEqual([]);
  expect(result.code).toStrictEqual(0);
});

test("self-test reads no file, so it runs against a root that does not exist", async () => {
  const result = await runCli(["self-test", "--root", "/no/such/tree"]);
  expect(result.code).toStrictEqual(0);
});

test("self-test leaves the tree it is pointed at untouched", async () => {
  await withGoodTree(async (root) => {
    const before = await snapshotTree(root);
    expect((await runCli(["self-test", "--root", root])).code).toStrictEqual(0);
    expect(await snapshotTree(root)).toStrictEqual(before);
  });
});

test("self-test fails when the digest it computes stops matching its vector", async () => {
  await withEmptyDir(async (dir) => {
    // Stops the blank lines after the frontmatter from being absorbed into
    // the separator, which changes what every contract digests to.
    const result = await runAltered(
      dir,
      "digest.ts",
      'while (start < lines.length && lines[start] === "") start++;',
      'while (start < lines.length && lines[start] === "\\u0000") start++;',
    );
    expect(result.code).toStrictEqual(1);
    expect(result.stdout.length > 0).toStrictEqual(true);
    expect(result.stdout.join("\n")).toContain("self-test:");
  });
});

test("self-test fails when the vendored copy header stops matching its vector", async () => {
  await withEmptyDir(async (dir) => {
    const result = await runAltered(
      dir,
      "header.ts",
      "<!-- DO NOT EDIT. Generated by ${GENERATOR_NAME}. -->",
      "<!-- DO NOT EDIT. Made by ${GENERATOR_NAME}. -->",
    );
    expect(result.code).toStrictEqual(1);
    expect(result.stdout.join("\n")).toContain("self-test:");
  });
});

test("self-test fails when the conformance framing stops matching its vector", async () => {
  await withEmptyDir(async (dir) => {
    const result = await runAltered(
      dir,
      "raw.ts",
      "encoder.encode(`${entry.path}\\0${entry.content.length}\\0`)",
      "encoder.encode(`${entry.path}\\0${entry.content.length}\\0\\0`)",
    );
    expect(result.code).toStrictEqual(1);
    expect(result.stdout.join("\n")).toContain("self-test:");
  });
});
