// selftest.ts — a smoke check that the tool computes what it is meant to.
//
// It answers one question: does this tool, in this environment, still produce
// the values its rules define? It is not a completeness check and proves
// nothing about which version is running — a tool cannot vouch for itself. Its
// use is catching an environment where the primitives it stands on behave
// differently from the ones the vectors were computed against.
//
// The vectors below were normalized and hashed by hand, outside this code, so
// they are an independent statement of the answer rather than a recording of
// whatever the implementation happened to produce.

import type { Sink } from "./errors.ts";
import { contractDigest, DIGEST_PREFIX } from "./digest.ts";
import { conformanceDigestOfEntries } from "./conformance.ts";
import { renderVendorFile } from "./gen.ts";

const SELF_TEST_DOCUMENT =
  '---\r\nversion: "1"\r\n---\r\n\r\nHello  \r\nWorld\r\n\r\n\r\n';
const SELF_TEST_DIGEST =
  "sha256:f5755ff05efa18e544073833aa1963073a8eb5f80a817564228b5b44a27bd96a";
const SELF_TEST_CONFORMANCE =
  "sha256:7bfb47738b94157bbf9d0b7de2a62a9c775f5bd67891dadf284be77d2bddea2e";
const SELF_TEST_HEADER =
  "<!-- DO NOT EDIT. Generated by agentic-skill-vendor. -->\n" +
  "<!-- contract: sample-contract -->\n" +
  "<!-- source-digest: sha256:" +
  "0".repeat(64) +
  " -->\n\nBody\n";

async function selfTestFailures(): Promise<string[]> {
  const encoder = new TextEncoder();
  const checks = [
    {
      name: "contract digest",
      expected: SELF_TEST_DIGEST,
      computed: await contractDigest(SELF_TEST_DOCUMENT),
    },
    {
      name: "conformance framing",
      expected: SELF_TEST_CONFORMANCE,
      computed: await conformanceDigestOfEntries([
        { path: "b.txt", content: encoder.encode("B\n") },
        { path: "a/x.txt", content: encoder.encode("XY") },
      ]),
    },
    {
      name: "vendored copy header",
      expected: SELF_TEST_HEADER,
      computed: renderVendorFile(
        "sample-contract",
        `${DIGEST_PREFIX}${"0".repeat(64)}`,
        "Body\n",
      ),
    },
  ];
  return checks
    .filter((check) => check.computed !== check.expected)
    .map(
      (check) =>
        `self-test: ${check.name}: computed ${JSON.stringify(check.computed)}, ` +
        `the embedded vector says ${JSON.stringify(check.expected)}`,
    );
}

/** Checks this file against its own vectors. Reads and writes nothing. */
export async function commandSelfTest(out: Sink): Promise<number> {
  const failures = await selfTestFailures();
  for (const failure of failures) out(failure);
  return failures.length > 0 ? 1 : 0;
}
